// <auto-generated />
namespace IronJS.Tests.UnitTests.Sputnik.Conformance.NativeECMAScriptObjects.ArrayObjects.TheArrayConstructor
{
    using System;
    using Microsoft.VisualStudio.TestTools.UnitTesting;

    [TestClass]
    public class NewArrayLenTests : SputnikTestFixture
    {
        public NewArrayLenTests()
            : base(@"Conformance\15_Native_ECMA_Script_Objects\15.4_Array_Objects\15.4.2_The_Array_Constructor\15.4.2.2_new_Array_len")
        {
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.4.2.2")]
        [Description("The [[Prototype]] property of the newly constructed object is set to the original Array prototype object, the one that is the initial value of Array.prototype")]
        public void S15_4_2_2_A1_1_T1()
        {
            RunFile(@"S15.4.2.2_A1.1_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.4.2.2")]
        [TestCategory("ECMA 15.2.4.2")]
        [Description("The [[Prototype]] property of the newly constructed object is set to the original Array prototype object, the one that is the initial value of Array.prototype")]
        public void S15_4_2_2_A1_1_T2()
        {
            RunFile(@"S15.4.2.2_A1.1_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.4.2.2")]
        [TestCategory("ECMA 15.2.4.6")]
        [Description("The [[Prototype]] property of the newly constructed object is set to the original Array prototype object, the one that is the initial value of Array.prototype")]
        public void S15_4_2_2_A1_1_T3()
        {
            RunFile(@"S15.4.2.2_A1.1_T3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.4.2.2")]
        [TestCategory("ECMA 15.2.4.2")]
        [Description("The [[Class]] property of the newly constructed object is set to \"Array\"")]
        public void S15_4_2_2_A1_2_T1()
        {
            RunFile(@"S15.4.2.2_A1.2_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.4.2.2")]
        [Description("If the argument len is a Number and ToUint32(len) is equal to len, then the length property of the newly constructed object is set to ToUint32(len)")]
        public void S15_4_2_2_A2_1_T1()
        {
            RunFile(@"S15.4.2.2_A2.1_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.4.2.2")]
        [TestCategory("ECMA 12.14")]
        [Description("If the argument len is a Number and ToUint32(len) is not equal to len, a RangeError exception is thrown")]
        public void S15_4_2_2_A2_2_T1()
        {
            RunFile(@"S15.4.2.2_A2.2_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.4.2.2")]
        [Description("If the argument len is a Number and ToUint32(len) is not equal to len, a RangeError exception is thrown")]
        public void S15_4_2_2_A2_2_T2()
        {
            RunFile(@"S15.4.2.2_A2.2_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.4.2.2")]
        [Description("If the argument len is a Number and ToUint32(len) is not equal to len, a RangeError exception is thrown")]
        public void S15_4_2_2_A2_2_T3()
        {
            RunFile(@"S15.4.2.2_A2.2_T3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.4.2.2")]
        [Description("If the argument len is not a Number, then the length property of the newly constructed object is set to 1 and the 0 property of the newly constructed object is set to len")]
        public void S15_4_2_2_A2_3_T1()
        {
            RunFile(@"S15.4.2.2_A2.3_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.4.2.2")]
        [Description("If the argument len is not a Number, then the length property of the newly constructed object is set to 1 and the 0 property of the newly constructed object is set to len")]
        public void S15_4_2_2_A2_3_T2()
        {
            RunFile(@"S15.4.2.2_A2.3_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.4.2.2")]
        [Description("If the argument len is not a Number, then the length property of the newly constructed object is set to 1 and the 0 property of the newly constructed object is set to len")]
        public void S15_4_2_2_A2_3_T3()
        {
            RunFile(@"S15.4.2.2_A2.3_T3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.4.2.2")]
        [Description("If the argument len is not a Number, then the length property of the newly constructed object is set to 1 and the 0 property of the newly constructed object is set to len")]
        public void S15_4_2_2_A2_3_T4()
        {
            RunFile(@"S15.4.2.2_A2.3_T4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.4.2.2")]
        [Description("If the argument len is not a Number, then the length property of the newly constructed object is set to 1 and the 0 property of the newly constructed object is set to len")]
        public void S15_4_2_2_A2_3_T5()
        {
            RunFile(@"S15.4.2.2_A2.3_T5.js");
        }
    }
}