// <auto-generated />
namespace IronJS.Tests.UnitTests.Sputnik.Conformance.NativeECMAScriptObjects.FunctionObjects.PropertiesOfTheFunctionPrototypeObject
{
    using System;
    using Microsoft.VisualStudio.TestTools.UnitTesting;

    [TestClass]
    public class FunctionPrototypeToStringTests : SputnikTestFixture
    {
        public FunctionPrototypeToStringTests()
            : base(@"Conformance\15_Native_ECMA_Script_Objects\15.3_Function_Objects\15.3.4_Properties_of_the_Function_Prototype_Object\15.3.4.2_Function.prototype.toString")
        {
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.2")]
        [Description("An implementation-dependent representation of the function is returned. This representation has the syntax of a FunctionDeclaration")]
        public void S15_3_4_2_A1_T1()
        {
            RunFile(@"S15.3.4.2_A1_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.2")]
        [Description("The Function.prototype.toString.length property has the attribute ReadOnly")]
        public void S15_3_4_2_A10()
        {
            RunFile(@"S15.3.4.2_A10.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.2")]
        [Description("The length property of the toString method is 0")]
        public void S15_3_4_2_A11()
        {
            RunFile(@"S15.3.4.2_A11.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.2")]
        [TestCategory("ECMA 13.2")]
        [Description("Function.prototype.toString has not prototype property")]
        public void S15_3_4_2_A6()
        {
            RunFile(@"S15.3.4.2_A6.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.2")]
        [TestCategory("ECMA 13.2")]
        [Description("Function.prototype.toString can\'t be used as constructor")]
        public void S15_3_4_2_A7()
        {
            RunFile(@"S15.3.4.2_A7.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.2")]
        [Description("The Function.prototype.toString.length property has the attribute DontEnum")]
        public void S15_3_4_2_A8()
        {
            RunFile(@"S15.3.4.2_A8.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.2")]
        [Description("The Function.prototype.toString.length property has the attribute DontDelete")]
        public void S15_3_4_2_A9()
        {
            RunFile(@"S15.3.4.2_A9.js");
        }
    }
}