// <auto-generated />
namespace IronJS.Tests.UnitTests.Sputnik.Conformance.NativeECMAScriptObjects.FunctionObjects.PropertiesOfTheFunctionPrototypeObject
{
    using System;
    using Microsoft.VisualStudio.TestTools.UnitTesting;

    [TestClass]
    public class FunctionPrototypeCallTests : SputnikTestFixture
    {
        public FunctionPrototypeCallTests()
            : base(@"Conformance\15_Native_ECMA_Script_Objects\15.3_Function_Objects\15.3.4_Properties_of_the_Function_Prototype_Object\15.3.4.4_Function.prototype.call")
        {
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("The call method performs a function call using the [[Call]] property of the object. If the object does not have a [[Call]] property, a TypeError exception is thrown")]
        public void S15_3_4_4_A1_T1()
        {
            RunFile(@"S15.3.4.4_A1_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("The call method performs a function call using the [[Call]] property of the object. If the object does not have a [[Call]] property, a TypeError exception is thrown")]
        public void S15_3_4_4_A1_T2()
        {
            RunFile(@"S15.3.4.4_A1_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("The Function.prototype.call.length property has the attribute ReadOnly")]
        public void S15_3_4_4_A10()
        {
            RunFile(@"S15.3.4.4_A10.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("The Function.prototype.call.length property has the attribute DontEnum")]
        public void S15_3_4_4_A11()
        {
            RunFile(@"S15.3.4.4_A11.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [TestCategory("ECMA 13.2")]
        [Description("Function.prototype.call has not prototype property")]
        public void S15_3_4_4_A12()
        {
            RunFile(@"S15.3.4.4_A12.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("The length property of the call method is 1")]
        public void S15_3_4_4_A2_T1()
        {
            RunFile(@"S15.3.4.4_A2_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("The length property of the call method is 1")]
        public void S15_3_4_4_A2_T2()
        {
            RunFile(@"S15.3.4.4_A2_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("If thisArg is null or undefined, the called function is passed the global object as the this value")]
        public void S15_3_4_4_A3_T1()
        {
            RunFile(@"S15.3.4.4_A3_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("If thisArg is null or undefined, the called function is passed the global object as the this value")]
        public void S15_3_4_4_A3_T10()
        {
            RunFile(@"S15.3.4.4_A3_T10.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("If thisArg is null or undefined, the called function is passed the global object as the this value")]
        public void S15_3_4_4_A3_T2()
        {
            RunFile(@"S15.3.4.4_A3_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("If thisArg is null or undefined, the called function is passed the global object as the this value")]
        public void S15_3_4_4_A3_T3()
        {
            RunFile(@"S15.3.4.4_A3_T3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("If thisArg is null or undefined, the called function is passed the global object as the this value")]
        public void S15_3_4_4_A3_T4()
        {
            RunFile(@"S15.3.4.4_A3_T4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("If thisArg is null or undefined, the called function is passed the global object as the this value")]
        public void S15_3_4_4_A3_T5()
        {
            RunFile(@"S15.3.4.4_A3_T5.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("If thisArg is null or undefined, the called function is passed the global object as the this value")]
        public void S15_3_4_4_A3_T6()
        {
            RunFile(@"S15.3.4.4_A3_T6.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("If thisArg is null or undefined, the called function is passed the global object as the this value")]
        public void S15_3_4_4_A3_T7()
        {
            RunFile(@"S15.3.4.4_A3_T7.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("If thisArg is null or undefined, the called function is passed the global object as the this value")]
        public void S15_3_4_4_A3_T8()
        {
            RunFile(@"S15.3.4.4_A3_T8.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("If thisArg is null or undefined, the called function is passed the global object as the this value")]
        public void S15_3_4_4_A3_T9()
        {
            RunFile(@"S15.3.4.4_A3_T9.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("If thisArg is not null(defined) the called function is passed ToObject(thisArg) as the this value")]
        public void S15_3_4_4_A5_T1()
        {
            RunFile(@"S15.3.4.4_A5_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("If thisArg is not null(defined) the called function is passed ToObject(thisArg) as the this value")]
        public void S15_3_4_4_A5_T2()
        {
            RunFile(@"S15.3.4.4_A5_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("If thisArg is not null(defined) the called function is passed ToObject(thisArg) as the this value")]
        public void S15_3_4_4_A5_T3()
        {
            RunFile(@"S15.3.4.4_A5_T3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("If thisArg is not null(defined) the called function is passed ToObject(thisArg) as the this value")]
        public void S15_3_4_4_A5_T4()
        {
            RunFile(@"S15.3.4.4_A5_T4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("If thisArg is not null(defined) the called function is passed ToObject(thisArg) as the this value")]
        public void S15_3_4_4_A5_T5()
        {
            RunFile(@"S15.3.4.4_A5_T5.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("If thisArg is not null(defined) the called function is passed ToObject(thisArg) as the this value")]
        public void S15_3_4_4_A5_T6()
        {
            RunFile(@"S15.3.4.4_A5_T6.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("If thisArg is not null(defined) the called function is passed ToObject(thisArg) as the this value")]
        public void S15_3_4_4_A5_T7()
        {
            RunFile(@"S15.3.4.4_A5_T7.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("If thisArg is not null(defined) the called function is passed ToObject(thisArg) as the this value")]
        public void S15_3_4_4_A5_T8()
        {
            RunFile(@"S15.3.4.4_A5_T8.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("The call method takes one or more arguments, thisArg and (optionally) arg1, arg2 etc, and performs a function call using the [[Call]] property of the object")]
        public void S15_3_4_4_A6_T1()
        {
            RunFile(@"S15.3.4.4_A6_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("The call method takes one or more arguments, thisArg and (optionally) arg1, arg2 etc, and performs a function call using the [[Call]] property of the object")]
        public void S15_3_4_4_A6_T10()
        {
            RunFile(@"S15.3.4.4_A6_T10.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("The call method takes one or more arguments, thisArg and (optionally) arg1, arg2 etc, and performs a function call using the [[Call]] property of the object")]
        public void S15_3_4_4_A6_T2()
        {
            RunFile(@"S15.3.4.4_A6_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("The call method takes one or more arguments, thisArg and (optionally) arg1, arg2 etc, and performs a function call using the [[Call]] property of the object")]
        public void S15_3_4_4_A6_T3()
        {
            RunFile(@"S15.3.4.4_A6_T3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("The call method takes one or more arguments, thisArg and (optionally) arg1, arg2 etc, and performs a function call using the [[Call]] property of the object")]
        public void S15_3_4_4_A6_T4()
        {
            RunFile(@"S15.3.4.4_A6_T4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("The call method takes one or more arguments, thisArg and (optionally) arg1, arg2 etc, and performs a function call using the [[Call]] property of the object")]
        public void S15_3_4_4_A6_T5()
        {
            RunFile(@"S15.3.4.4_A6_T5.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("The call method takes one or more arguments, thisArg and (optionally) arg1, arg2 etc, and performs a function call using the [[Call]] property of the object")]
        public void S15_3_4_4_A6_T6()
        {
            RunFile(@"S15.3.4.4_A6_T6.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("The call method takes one or more arguments, thisArg and (optionally) arg1, arg2 etc, and performs a function call using the [[Call]] property of the object")]
        public void S15_3_4_4_A6_T7()
        {
            RunFile(@"S15.3.4.4_A6_T7.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("The call method takes one or more arguments, thisArg and (optionally) arg1, arg2 etc, and performs a function call using the [[Call]] property of the object")]
        public void S15_3_4_4_A6_T8()
        {
            RunFile(@"S15.3.4.4_A6_T8.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("The call method takes one or more arguments, thisArg and (optionally) arg1, arg2 etc, and performs a function call using the [[Call]] property of the object")]
        public void S15_3_4_4_A6_T9()
        {
            RunFile(@"S15.3.4.4_A6_T9.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("Function.prototype.call can\'t be used as [[create]] caller")]
        public void S15_3_4_4_A7_T1()
        {
            RunFile(@"S15.3.4.4_A7_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("Function.prototype.call can\'t be used as [[create]] caller")]
        public void S15_3_4_4_A7_T2()
        {
            RunFile(@"S15.3.4.4_A7_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("Function.prototype.call can\'t be used as [[create]] caller")]
        public void S15_3_4_4_A7_T3()
        {
            RunFile(@"S15.3.4.4_A7_T3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("Function.prototype.call can\'t be used as [[create]] caller")]
        public void S15_3_4_4_A7_T4()
        {
            RunFile(@"S15.3.4.4_A7_T4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("Function.prototype.call can\'t be used as [[create]] caller")]
        public void S15_3_4_4_A7_T5()
        {
            RunFile(@"S15.3.4.4_A7_T5.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("Function.prototype.call can\'t be used as [[create]] caller")]
        public void S15_3_4_4_A7_T6()
        {
            RunFile(@"S15.3.4.4_A7_T6.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.3.4.4")]
        [Description("The Function.prototype.call.length property has the attribute DontDelete")]
        public void S15_3_4_4_A9()
        {
            RunFile(@"S15.3.4.4_A9.js");
        }
    }
}