// <auto-generated />
namespace IronJS.Tests.UnitTests.IE9.chapter12
{
    using System;
    using NUnit.Framework;

    [TestFixture]
    public class _12_7_Tests : IE9TestFixture
    {
        public _12_7_Tests() : base(@"chapter12\12.7") { }

        [Test(Description = "The continue Statement - a continue statement without an identifier may have a LineTerminator before the semi-colon")] public void _12_7__1() { RunFile(@"12.7-1.js"); }
    }
}