// <auto-generated />
namespace IronJS.Tests.UnitTests.IE9.chapter12
{
    using System;
    using NUnit.Framework;

    [TestFixture]
    public class _12_8_Tests : IE9TestFixture
    {
        public _12_8_Tests() : base(@"chapter12\12.8") { }

        [Test(Description = "The break Statement - a break statement without an identifier may have a LineTerminator before the semi-colon")] public void _12_8__1() { RunFile(@"12.8-1.js"); }
    }
}