// <auto-generated />
namespace IronJS.Tests.UnitTests.Sputnik.Conformance.NativeECMAScriptObjects.RegExpObjects.PatternSemantics
{
    using System;
    using Microsoft.VisualStudio.TestTools.UnitTesting;

    [TestClass]
    public class DecimalEscapeTests : SputnikTestFixture
    {
        public DecimalEscapeTests()
            : base(@"Conformance\15_Native_ECMA_Script_Objects\15.10_RegExp_Objects\15.10.2_Pattern_Semantics\15.10.2.11_DecimalEscape")
        {
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.10.2.11")]
        [Description("DecimalEscape :: DecimalIntegerLiteral [lookahead not in DecimalDigit]")]
        public void S15_10_2_11_A1_T1()
        {
            RunFile(@"S15.10.2.11_A1_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.10.2.11")]
        [Description("DecimalEscape :: DecimalIntegerLiteral [lookahead not in DecimalDigit]")]
        public void S15_10_2_11_A1_T2()
        {
            RunFile_ExpectException(@"S15.10.2.11_A1_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.10.2.11")]
        [Description("DecimalEscape :: DecimalIntegerLiteral [lookahead not in DecimalDigit]")]
        public void S15_10_2_11_A1_T3()
        {
            RunFile_ExpectException(@"S15.10.2.11_A1_T3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.10.2.11")]
        [TestCategory("ECMA 15.10.2.9")]
        [Description("DecimalEscape :: DecimalIntegerLiteral [lookahead not in DecimalDigit]")]
        public void S15_10_2_11_A1_T4()
        {
            RunFile(@"S15.10.2.11_A1_T4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.10.2.11")]
        [TestCategory("ECMA 15.10.2.9")]
        [Description("DecimalEscape :: DecimalIntegerLiteral [lookahead not in DecimalDigit]")]
        public void S15_10_2_11_A1_T5()
        {
            RunFile(@"S15.10.2.11_A1_T5.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.10.2.11")]
        [TestCategory("ECMA 15.10.2.9")]
        [Description("DecimalEscape :: DecimalIntegerLiteral [lookahead not in DecimalDigit]")]
        public void S15_10_2_11_A1_T6()
        {
            RunFile(@"S15.10.2.11_A1_T6.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.10.2.11")]
        [TestCategory("ECMA 15.10.2.9")]
        [Description("DecimalEscape :: DecimalIntegerLiteral [lookahead not in DecimalDigit]")]
        public void S15_10_2_11_A1_T7()
        {
            RunFile(@"S15.10.2.11_A1_T7.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.10.2.11")]
        [TestCategory("ECMA 15.10.2.9")]
        [Description("DecimalEscape :: DecimalIntegerLiteral [lookahead not in DecimalDigit]")]
        public void S15_10_2_11_A1_T8()
        {
            RunFile(@"S15.10.2.11_A1_T8.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.10.2.11")]
        [TestCategory("ECMA 15.10.2.9")]
        [Description("DecimalEscape :: DecimalIntegerLiteral [lookahead not in DecimalDigit]")]
        public void S15_10_2_11_A1_T9()
        {
            RunFile(@"S15.10.2.11_A1_T9.js");
        }
    }
}