// <auto-generated />
namespace IronJS.Tests.UnitTests.Sputnik.Conformance.NativeECMAScriptObjects.TheMathObject.FunctionPropertiesOfTheMathObject
{
    using System;
    using NUnit.Framework;

    [TestFixture]
    public class MaxTests : SputnikTestFixture
    {
        public MaxTests()
            : base(@"Conformance\15_Native_ECMA_Script_Objects\15.8_The_Math_Object\15.8.2_Function_Properties_of_the_Math_Object\15.8.2.11_max")
        {
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.8.2.11")]
        [TestCase("S15.8.2.11_A1.js", Description = "If no arguments are given, Math.max() is -Infinity")]
        public void IfNoArgumentsAreGivenMathMaxIsInfinity(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.8.2.11")]
        [TestCase("S15.8.2.11_A2.js", Description = "If any value is NaN, the result of Math.max is NaN")]
        public void IfAnyValueIsNaNTheResultOfMathMaxIsNaN(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.8.2.11")]
        [TestCase("S15.8.2.11_A3.js", Description = "+0 is considered to be larger than -0")]
        public void _0IsConsideredToBeLargerThan0(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.8.2.11")]
        [TestCase("S15.8.2.11_A4.js", Description = "The length property of the Math.max method is 2")]
        public void TheLengthPropertyOfTheMathMaxMethodIs2(string file)
        {
            RunFile(file);
        }
    }
}