// <auto-generated />
namespace IronJS.Tests.UnitTests.Sputnik.Conformance.NativeECMAScriptObjects.TheGlobalObject
{
    using System;
    using Microsoft.VisualStudio.TestTools.UnitTesting;

    [TestClass]
    public class TheGlobalObjectTests : SputnikTestFixture
    {
        public TheGlobalObjectTests()
            : base(@"Conformance\15_Native_ECMA_Script_Objects\15.1_The_Global_Object")
        {
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.1")]
        [Description("The global object does not have a [[Construct]] property")]
        public void S15_1_A1_T1()
        {
            RunFile_ExpectException(@"S15.1_A1_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.1")]
        [Description("The global object does not have a [[Construct]] property")]
        public void S15_1_A1_T2()
        {
            RunFile_ExpectException(@"S15.1_A1_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.1")]
        [Description("The global object does not have a [[Call]] property")]
        public void S15_1_A2_T1()
        {
            RunFile_ExpectException(@"S15.1_A2_T1.js");
        }
    }
}