// <auto-generated />
namespace IronJS.Tests.UnitTests.IE9.chapter15._15_1._15_1_1
{
    using System;
    using NUnit.Framework;

    [TestFixture]
    public class _15_1_1_2_Tests : IE9TestFixture
    {
        public _15_1_1_2_Tests() : base(@"chapter15\15.1\15.1.1\15.1.1.2") { }

        [Test(Description = "Global.Infinity is a data property with default attribute values (false)")] public void _15_1_1_2__0() { RunFile(@"15.1.1.2-0.js"); }
    }
}