// <auto-generated />
namespace IronJS.Tests.UnitTests.Sputnik.Conformance.Statement.IterationStatements
{
    using System;
    using Microsoft.VisualStudio.TestTools.UnitTesting;

    [TestClass]
    public class TheForInStatementTests : SputnikTestFixture
    {
        public TheForInStatementTests()
            : base(@"Conformance\12_Statement\12.6_Iteration_Statements\12.6.4_The_for_in_Statement")
        {
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 12.6.4")]
        [Description("\"for(key in undefined)\" Statement is allowed")]
        public void S12_6_4_A1()
        {
            RunFile(@"S12.6.4_A1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 12.6.4")]
        [Description("FunctionDeclaration within a \"for-in\" Statement is not allowed")]
        public void S12_6_4_A13_T1()
        {
            RunFile_ExpectException(@"S12.6.4_A13_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 12.6.4")]
        [Description("FunctionDeclaration within a \"for-in\" Statement is not allowed")]
        public void S12_6_4_A13_T2()
        {
            RunFile_ExpectException(@"S12.6.4_A13_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 12.6.4")]
        [Description("FunctionDeclaration within a \"for-in\" Statement is not allowed")]
        public void S12_6_4_A13_T3()
        {
            RunFile_ExpectException(@"S12.6.4_A13_T3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 12.6.4")]
        [Description("FunctionExpession within a \"for-in\" Expression is allowed")]
        public void S12_6_4_A14_T1()
        {
            RunFile(@"S12.6.4_A14_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 12.6.4")]
        [Description("FunctionExpession within a \"for-in\" Expression is allowed")]
        public void S12_6_4_A14_T2()
        {
            RunFile(@"S12.6.4_A14_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 12.6.4")]
        [Description("Block within a \"for-in\" Expression is not allowed")]
        public void S12_6_4_A15()
        {
            RunFile_ExpectException(@"S12.6.4_A15.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 12.6.4")]
        [Description("\"for(key in null)\" Expression is allowed")]
        public void S12_6_4_A2()
        {
            RunFile(@"S12.6.4_A2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 12.6.4")]
        [Description("The production IterationStatement: \"for (var VariableDeclarationNoIn in Expression) Statement\"")]
        public void S12_6_4_A3()
        {
            RunFile(@"S12.6.4_A3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 12.6.4")]
        [Description("The production IterationStatement: \"for (var VariableDeclarationNoIn in Expression) Statement\"")]
        public void S12_6_4_A3_1()
        {
            RunFile(@"S12.6.4_A3.1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 12.6.4")]
        [Description("The production IterationStatement: \"for (var VariableDeclarationNoIn in Expression) Statement\"")]
        public void S12_6_4_A4()
        {
            RunFile(@"S12.6.4_A4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 12.6.4")]
        [Description("The production IterationStatement: \"for (var VariableDeclarationNoIn in Expression) Statement\"")]
        public void S12_6_4_A4_1()
        {
            RunFile(@"S12.6.4_A4.1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 12.6.4")]
        [Description("The production IterationStatement: \"for (var VariableDeclarationNoIn in Expression) Statement\"")]
        public void S12_6_4_A5()
        {
            RunFile(@"S12.6.4_A5.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 12.6.4")]
        [Description("The production IterationStatement: \"for (var VariableDeclarationNoIn in Expression) Statement\"")]
        public void S12_6_4_A5_1()
        {
            RunFile(@"S12.6.4_A5.1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 12.6.4")]
        [Description("The production IterationStatement: \"for (var VariableDeclarationNoIn in Expression) Statement\"")]
        public void S12_6_4_A6()
        {
            RunFile(@"S12.6.4_A6.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 12.6.4")]
        [Description("The production IterationStatement: \"for (var VariableDeclarationNoIn in Expression) Statement\"")]
        public void S12_6_4_A6_1()
        {
            RunFile(@"S12.6.4_A6.1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 12.6.4")]
        [Description("Properties of the object being enumerated may be deleted during enumeration")]
        public void S12_6_4_A7_T1()
        {
            RunFile(@"S12.6.4_A7_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 12.6.4")]
        [Description("Properties of the object being enumerated may be deleted during enumeration")]
        public void S12_6_4_A7_T2()
        {
            RunFile(@"S12.6.4_A7_T2.js");
        }
    }
}