// <auto-generated />
namespace IronJS.Tests.UnitTests.Sputnik.Conformance.NativeECMAScriptObjects.TheGlobalObject.ValuePropertiesOfTheGlobalObject
{
    using System;
    using NUnit.Framework;

    [TestFixture]
    public class InfinityTests : SputnikTestFixture
    {
        public InfinityTests()
            : base(@"Conformance\15_Native_ECMA_Script_Objects\15.1_The_Global_Object\15.1.1_Value_Properties_of_the_Global_Object\15.1.1.2_Infinity")
        {
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 11.4.3")]
        [Category("ECMA 15.1.1.2")]
        [Category("ECMA 15.1.2.4")]
        [Category("ECMA 15.1.2.5")]
        [TestCase("S15.1.1.2_A1.js", Description = "The initial value of Infinity is Number.POSITIVE_INFINITY")]
        public void TheInitialValueOfInfinityIsNumberPOSITIVE_INFINITY(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 11.4.3")]
        [Category("ECMA 15.1.1.2")]
        [Category("ECMA 15.5.1")]
        [Category("ECMA 15.6.1")]
        [Category("ECMA 15.7.1")]
        [TestCase("S15.1.1.2_A2_T1.js", Description = "The Infinity is not ReadOnly")]
        [TestCase("S15.1.1.2_A2_T2.js", Description = "The Infinity is not ReadOnly")]
        public void TheInfinityIsNotReadOnly(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 11.4.1")]
        [Category("ECMA 15.1.1.2")]
        [TestCase("S15.1.1.2_A3.1.js", Description = "The Infinity is DontDelete")]
        public void TheInfinityIsDontDelete(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 12.6.4")]
        [Category("ECMA 15.1.1.2")]
        [TestCase("S15.1.1.2_A3.2.js", Description = "The Infinity is DontEnum")]
        public void TheInfinityIsDontEnum(string file)
        {
            RunFile(file);
        }
    }
}