// <auto-generated />
namespace IronJS.Tests.UnitTests.IE9.chapter15._15_1._15_1_2
{
    using System;
    using NUnit.Framework;

    [TestFixture]
    public class _15_1_2_3_Tests : IE9TestFixture
    {
        public _15_1_2_3_Tests() : base(@"chapter15\15.1\15.1.2\15.1.2.3") { }

        [Test(Description = "pareseFloat - \'trimmedString\' is the empty string when inputString does not contain any such characters")] public void _15_1_2_3__2__1() { RunFile(@"15.1.2.3-2-1.js"); }
    }
}