// <auto-generated />
namespace IronJS.Tests.UnitTests.Sputnik.Conformance.NativeECMAScriptObjects.ArrayObjects.PropertiesOfArrayInstances
{
    using System;
    using Microsoft.VisualStudio.TestTools.UnitTesting;

    [TestClass]
    public class LengthTests : SputnikTestFixture
    {
        public LengthTests()
            : base(@"Conformance\15_Native_ECMA_Script_Objects\15.4_Array_Objects\15.4.5_Properties_of_Array_Instances\15.4.5.2_length")
        {
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.4.5.2")]
        [TestCategory("ECMA 15.4")]
        [Description("Every Array object has a length property whose value is always a nonnegative integer less than 2^32. The value of the length property is numerically greater than the name of every property whose name is an array index")]
        public void S15_4_5_2_A1_T1()
        {
            RunFile(@"S15.4.5.2_A1_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.4.5.2")]
        [TestCategory("ECMA 15.4")]
        [Description("Every Array object has a length property whose value is always a nonnegative integer less than 2^32. The value of the length property is numerically greater than the name of every property whose name is an array index")]
        public void S15_4_5_2_A1_T2()
        {
            RunFile(@"S15.4.5.2_A1_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.4.5.2")]
        [TestCategory("ECMA 15.4")]
        [Description("If a property is added whose name is an array index, the length property is changed")]
        public void S15_4_5_2_A2_T1()
        {
            RunFile(@"S15.4.5.2_A2_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.4.5.2")]
        [TestCategory("ECMA 15.4")]
        [Description("If the length property is changed, every property whose name is an array index whose value is not smaller than the new length is automatically deleted")]
        public void S15_4_5_2_A3_T1()
        {
            RunFile(@"S15.4.5.2_A3_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.4.5.2")]
        [TestCategory("ECMA 15.4")]
        [Description("If the length property is changed, every property whose name is an array index whose value is not smaller than the new length is automatically deleted")]
        public void S15_4_5_2_A3_T2()
        {
            RunFile(@"S15.4.5.2_A3_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.4.5.2")]
        [TestCategory("ECMA 15.4.2.2")]
        [Description("If the length property is changed, every property whose name is an array index whose value is not smaller than the new length is automatically deleted")]
        public void S15_4_5_2_A3_T3()
        {
            RunFile(@"S15.4.5.2_A3_T3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.4.5.2")]
        [TestCategory("ECMA 15.4.2.2")]
        [Description("If the length property is changed, every property whose name is an array index whose value is not smaller than the new length is automatically deleted")]
        public void S15_4_5_2_A3_T4()
        {
            RunFile(@"S15.4.5.2_A3_T4.js");
        }
    }
}