// <auto-generated />
namespace IronJS.Tests.UnitTests.Sputnik.Conformance.Expressions.AssignmentOperators
{
    using System;
    using Microsoft.VisualStudio.TestTools.UnitTesting;

    [TestClass]
    public class CompoundAssignmentTests : SputnikTestFixture
    {
        public CompoundAssignmentTests()
            : base(@"Conformance\11_Expressions\11.13_Assignment_Operators\11.13.2_Compound_Assignment")
        {
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("White Space and Line Terminator between LeftHandSideExpression and \"@=\" or between \"@=\" and AssignmentExpression are allowed")]
        public void S11_13_2_A1_T1()
        {
            RunFile(@"S11.13.2_A1_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("White Space and Line Terminator between LeftHandSideExpression and \"@=\" or between \"@=\" and AssignmentExpression are allowed")]
        public void S11_13_2_A1_T10()
        {
            RunFile(@"S11.13.2_A1_T10.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("White Space and Line Terminator between LeftHandSideExpression and \"@=\" or between \"@=\" and AssignmentExpression are allowed")]
        public void S11_13_2_A1_T11()
        {
            RunFile(@"S11.13.2_A1_T11.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("White Space and Line Terminator between LeftHandSideExpression and \"@=\" or between \"@=\" and AssignmentExpression are allowed")]
        public void S11_13_2_A1_T2()
        {
            RunFile(@"S11.13.2_A1_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("White Space and Line Terminator between LeftHandSideExpression and \"@=\" or between \"@=\" and AssignmentExpression are allowed")]
        public void S11_13_2_A1_T3()
        {
            RunFile(@"S11.13.2_A1_T3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("White Space and Line Terminator between LeftHandSideExpression and \"@=\" or between \"@=\" and AssignmentExpression are allowed")]
        public void S11_13_2_A1_T4()
        {
            RunFile(@"S11.13.2_A1_T4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("White Space and Line Terminator between LeftHandSideExpression and \"@=\" or between \"@=\" and AssignmentExpression are allowed")]
        public void S11_13_2_A1_T5()
        {
            RunFile(@"S11.13.2_A1_T5.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("White Space and Line Terminator between LeftHandSideExpression and \"@=\" or between \"@=\" and AssignmentExpression are allowed")]
        public void S11_13_2_A1_T6()
        {
            RunFile(@"S11.13.2_A1_T6.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("White Space and Line Terminator between LeftHandSideExpression and \"@=\" or between \"@=\" and AssignmentExpression are allowed")]
        public void S11_13_2_A1_T7()
        {
            RunFile(@"S11.13.2_A1_T7.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("White Space and Line Terminator between LeftHandSideExpression and \"@=\" or between \"@=\" and AssignmentExpression are allowed")]
        public void S11_13_2_A1_T8()
        {
            RunFile(@"S11.13.2_A1_T8.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("White Space and Line Terminator between LeftHandSideExpression and \"@=\" or between \"@=\" and AssignmentExpression are allowed")]
        public void S11_13_2_A1_T9()
        {
            RunFile(@"S11.13.2_A1_T9.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator uses GetValue")]
        public void S11_13_2_A2_1_T1_1()
        {
            RunFile(@"S11.13.2_A2.1_T1.1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator uses GetValue")]
        public void S11_13_2_A2_1_T1_10()
        {
            RunFile(@"S11.13.2_A2.1_T1.10.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator uses GetValue")]
        public void S11_13_2_A2_1_T1_11()
        {
            RunFile(@"S11.13.2_A2.1_T1.11.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator uses GetValue")]
        public void S11_13_2_A2_1_T1_2()
        {
            RunFile(@"S11.13.2_A2.1_T1.2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator uses GetValue")]
        public void S11_13_2_A2_1_T1_3()
        {
            RunFile(@"S11.13.2_A2.1_T1.3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator uses GetValue")]
        public void S11_13_2_A2_1_T1_4()
        {
            RunFile(@"S11.13.2_A2.1_T1.4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator uses GetValue")]
        public void S11_13_2_A2_1_T1_5()
        {
            RunFile(@"S11.13.2_A2.1_T1.5.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator uses GetValue")]
        public void S11_13_2_A2_1_T1_6()
        {
            RunFile(@"S11.13.2_A2.1_T1.6.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator uses GetValue")]
        public void S11_13_2_A2_1_T1_7()
        {
            RunFile(@"S11.13.2_A2.1_T1.7.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator uses GetValue")]
        public void S11_13_2_A2_1_T1_8()
        {
            RunFile(@"S11.13.2_A2.1_T1.8.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator uses GetValue")]
        public void S11_13_2_A2_1_T1_9()
        {
            RunFile(@"S11.13.2_A2.1_T1.9.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator uses GetValue")]
        public void S11_13_2_A2_1_T2_1()
        {
            RunFile(@"S11.13.2_A2.1_T2.1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator uses GetValue")]
        public void S11_13_2_A2_1_T2_10()
        {
            RunFile(@"S11.13.2_A2.1_T2.10.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator uses GetValue")]
        public void S11_13_2_A2_1_T2_11()
        {
            RunFile(@"S11.13.2_A2.1_T2.11.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator uses GetValue")]
        public void S11_13_2_A2_1_T2_2()
        {
            RunFile(@"S11.13.2_A2.1_T2.2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator uses GetValue")]
        public void S11_13_2_A2_1_T2_3()
        {
            RunFile(@"S11.13.2_A2.1_T2.3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator uses GetValue")]
        public void S11_13_2_A2_1_T2_4()
        {
            RunFile(@"S11.13.2_A2.1_T2.4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator uses GetValue")]
        public void S11_13_2_A2_1_T2_5()
        {
            RunFile(@"S11.13.2_A2.1_T2.5.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator uses GetValue")]
        public void S11_13_2_A2_1_T2_6()
        {
            RunFile(@"S11.13.2_A2.1_T2.6.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator uses GetValue")]
        public void S11_13_2_A2_1_T2_7()
        {
            RunFile(@"S11.13.2_A2.1_T2.7.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator uses GetValue")]
        public void S11_13_2_A2_1_T2_8()
        {
            RunFile(@"S11.13.2_A2.1_T2.8.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator uses GetValue")]
        public void S11_13_2_A2_1_T2_9()
        {
            RunFile(@"S11.13.2_A2.1_T2.9.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator uses GetValue")]
        public void S11_13_2_A2_1_T3_1()
        {
            RunFile(@"S11.13.2_A2.1_T3.1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator uses GetValue")]
        public void S11_13_2_A2_1_T3_10()
        {
            RunFile(@"S11.13.2_A2.1_T3.10.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator uses GetValue")]
        public void S11_13_2_A2_1_T3_11()
        {
            RunFile(@"S11.13.2_A2.1_T3.11.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator uses GetValue")]
        public void S11_13_2_A2_1_T3_2()
        {
            RunFile(@"S11.13.2_A2.1_T3.2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator uses GetValue")]
        public void S11_13_2_A2_1_T3_3()
        {
            RunFile(@"S11.13.2_A2.1_T3.3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator uses GetValue")]
        public void S11_13_2_A2_1_T3_4()
        {
            RunFile(@"S11.13.2_A2.1_T3.4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator uses GetValue")]
        public void S11_13_2_A2_1_T3_5()
        {
            RunFile(@"S11.13.2_A2.1_T3.5.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator uses GetValue")]
        public void S11_13_2_A2_1_T3_6()
        {
            RunFile(@"S11.13.2_A2.1_T3.6.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator uses GetValue")]
        public void S11_13_2_A2_1_T3_7()
        {
            RunFile(@"S11.13.2_A2.1_T3.7.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator uses GetValue")]
        public void S11_13_2_A2_1_T3_8()
        {
            RunFile(@"S11.13.2_A2.1_T3.8.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator uses GetValue")]
        public void S11_13_2_A2_1_T3_9()
        {
            RunFile(@"S11.13.2_A2.1_T3.9.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 16")]
        [Description("Operator uses PutValue")]
        public void S11_13_2_A2_2_T1()
        {
            RunFile_ExpectException(@"S11.13.2_A2.2_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 16")]
        [Description("Operator uses PutValue")]
        public void S11_13_2_A2_2_T10()
        {
            RunFile_ExpectException(@"S11.13.2_A2.2_T10.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 16")]
        [Description("Operator uses PutValue")]
        public void S11_13_2_A2_2_T11()
        {
            RunFile_ExpectException(@"S11.13.2_A2.2_T11.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 16")]
        [Description("Operator uses PutValue")]
        public void S11_13_2_A2_2_T2()
        {
            RunFile_ExpectException(@"S11.13.2_A2.2_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 16")]
        [Description("Operator uses PutValue")]
        public void S11_13_2_A2_2_T3()
        {
            RunFile_ExpectException(@"S11.13.2_A2.2_T3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 16")]
        [Description("Operator uses PutValue")]
        public void S11_13_2_A2_2_T4()
        {
            RunFile_ExpectException(@"S11.13.2_A2.2_T4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 16")]
        [Description("Operator uses PutValue")]
        public void S11_13_2_A2_2_T5()
        {
            RunFile_ExpectException(@"S11.13.2_A2.2_T5.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 16")]
        [Description("Operator uses PutValue")]
        public void S11_13_2_A2_2_T6()
        {
            RunFile_ExpectException(@"S11.13.2_A2.2_T6.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 16")]
        [Description("Operator uses PutValue")]
        public void S11_13_2_A2_2_T7()
        {
            RunFile_ExpectException(@"S11.13.2_A2.2_T7.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 16")]
        [Description("Operator uses PutValue")]
        public void S11_13_2_A2_2_T8()
        {
            RunFile_ExpectException(@"S11.13.2_A2.2_T8.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 16")]
        [Description("Operator uses PutValue")]
        public void S11_13_2_A2_2_T9()
        {
            RunFile_ExpectException(@"S11.13.2_A2.2_T9.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator x @= y uses PutValue(x, x @ y)")]
        public void S11_13_2_A3_1_T1()
        {
            RunFile(@"S11.13.2_A3.1_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator x @= y uses PutValue(x, x @ y)")]
        public void S11_13_2_A3_1_T10()
        {
            RunFile(@"S11.13.2_A3.1_T10.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator x @= y uses PutValue(x, x @ y)")]
        public void S11_13_2_A3_1_T11()
        {
            RunFile(@"S11.13.2_A3.1_T11.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator x @= y uses PutValue(x, x @ y)")]
        public void S11_13_2_A3_1_T2()
        {
            RunFile(@"S11.13.2_A3.1_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator x @= y uses PutValue(x, x @ y)")]
        public void S11_13_2_A3_1_T3()
        {
            RunFile(@"S11.13.2_A3.1_T3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator x @= y uses PutValue(x, x @ y)")]
        public void S11_13_2_A3_1_T4()
        {
            RunFile(@"S11.13.2_A3.1_T4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator x @= y uses PutValue(x, x @ y)")]
        public void S11_13_2_A3_1_T5()
        {
            RunFile(@"S11.13.2_A3.1_T5.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator x @= y uses PutValue(x, x @ y)")]
        public void S11_13_2_A3_1_T6()
        {
            RunFile(@"S11.13.2_A3.1_T6.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator x @= y uses PutValue(x, x @ y)")]
        public void S11_13_2_A3_1_T7()
        {
            RunFile(@"S11.13.2_A3.1_T7.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator x @= y uses PutValue(x, x @ y)")]
        public void S11_13_2_A3_1_T8()
        {
            RunFile(@"S11.13.2_A3.1_T8.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator x @= y uses PutValue(x, x @ y)")]
        public void S11_13_2_A3_1_T9()
        {
            RunFile(@"S11.13.2_A3.1_T9.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator x @= y returns x @ y")]
        public void S11_13_2_A3_2_T1()
        {
            RunFile(@"S11.13.2_A3.2_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator x @= y returns x @ y")]
        public void S11_13_2_A3_2_T10()
        {
            RunFile(@"S11.13.2_A3.2_T10.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator x @= y returns x @ y")]
        public void S11_13_2_A3_2_T11()
        {
            RunFile(@"S11.13.2_A3.2_T11.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator x @= y returns x @ y")]
        public void S11_13_2_A3_2_T2()
        {
            RunFile(@"S11.13.2_A3.2_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator x @= y returns x @ y")]
        public void S11_13_2_A3_2_T3()
        {
            RunFile(@"S11.13.2_A3.2_T3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator x @= y returns x @ y")]
        public void S11_13_2_A3_2_T4()
        {
            RunFile(@"S11.13.2_A3.2_T4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator x @= y returns x @ y")]
        public void S11_13_2_A3_2_T5()
        {
            RunFile(@"S11.13.2_A3.2_T5.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator x @= y returns x @ y")]
        public void S11_13_2_A3_2_T6()
        {
            RunFile(@"S11.13.2_A3.2_T6.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator x @= y returns x @ y")]
        public void S11_13_2_A3_2_T7()
        {
            RunFile(@"S11.13.2_A3.2_T7.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator x @= y returns x @ y")]
        public void S11_13_2_A3_2_T8()
        {
            RunFile(@"S11.13.2_A3.2_T8.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [Description("Operator x @= y returns x @ y")]
        public void S11_13_2_A3_2_T9()
        {
            RunFile(@"S11.13.2_A3.2_T9.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.1")]
        [Description("The production x *= y is the same as the production x = x * y")]
        public void S11_13_2_A4_1_T1_1()
        {
            RunFile(@"S11.13.2_A4.1_T1.1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.1")]
        [Description("The production x *= y is the same as the production x = x * y")]
        public void S11_13_2_A4_1_T1_2()
        {
            RunFile(@"S11.13.2_A4.1_T1.2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.1")]
        [Description("The production x *= y is the same as the production x = x * y")]
        public void S11_13_2_A4_1_T1_3()
        {
            RunFile(@"S11.13.2_A4.1_T1.3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.1")]
        [Description("The production x *= y is the same as the production x = x * y")]
        public void S11_13_2_A4_1_T1_4()
        {
            RunFile(@"S11.13.2_A4.1_T1.4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.1")]
        [Description("The production x *= y is the same as the production x = x * y")]
        public void S11_13_2_A4_1_T2_1()
        {
            RunFile(@"S11.13.2_A4.1_T2.1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.1")]
        [Description("The production x *= y is the same as the production x = x * y")]
        public void S11_13_2_A4_1_T2_2()
        {
            RunFile(@"S11.13.2_A4.1_T2.2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.1")]
        [Description("The production x *= y is the same as the production x = x * y")]
        public void S11_13_2_A4_1_T2_3()
        {
            RunFile(@"S11.13.2_A4.1_T2.3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.1")]
        [Description("The production x *= y is the same as the production x = x * y")]
        public void S11_13_2_A4_1_T2_4()
        {
            RunFile(@"S11.13.2_A4.1_T2.4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.1")]
        [Description("The production x *= y is the same as the production x = x * y")]
        public void S11_13_2_A4_1_T2_5()
        {
            RunFile(@"S11.13.2_A4.1_T2.5.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.1")]
        [Description("The production x *= y is the same as the production x = x * y")]
        public void S11_13_2_A4_1_T2_6()
        {
            RunFile(@"S11.13.2_A4.1_T2.6.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.1")]
        [Description("The production x *= y is the same as the production x = x * y")]
        public void S11_13_2_A4_1_T2_7()
        {
            RunFile(@"S11.13.2_A4.1_T2.7.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.1")]
        [Description("The production x *= y is the same as the production x = x * y")]
        public void S11_13_2_A4_1_T2_8()
        {
            RunFile(@"S11.13.2_A4.1_T2.8.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.1")]
        [Description("The production x *= y is the same as the production x = x * y")]
        public void S11_13_2_A4_1_T2_9()
        {
            RunFile(@"S11.13.2_A4.1_T2.9.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.2")]
        [Description("The production x ^= y is the same as x = x ^ y")]
        public void S11_13_2_A4_10_T1_1()
        {
            RunFile(@"S11.13.2_A4.10_T1.1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.2")]
        [Description("The production x ^= y is the same as x = x ^ y")]
        public void S11_13_2_A4_10_T1_2()
        {
            RunFile(@"S11.13.2_A4.10_T1.2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.2")]
        [Description("The production x ^= y is the same as x = x ^ y")]
        public void S11_13_2_A4_10_T1_3()
        {
            RunFile(@"S11.13.2_A4.10_T1.3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.2")]
        [Description("The production x ^= y is the same as x = x ^ y")]
        public void S11_13_2_A4_10_T1_4()
        {
            RunFile(@"S11.13.2_A4.10_T1.4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.2")]
        [Description("The production x ^= y is the same as x = x ^ y")]
        public void S11_13_2_A4_10_T2_1()
        {
            RunFile(@"S11.13.2_A4.10_T2.1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.2")]
        [Description("The production x ^= y is the same as x = x ^ y")]
        public void S11_13_2_A4_10_T2_2()
        {
            RunFile(@"S11.13.2_A4.10_T2.2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.2")]
        [Description("The production x ^= y is the same as x = x ^ y")]
        public void S11_13_2_A4_10_T2_3()
        {
            RunFile(@"S11.13.2_A4.10_T2.3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.2")]
        [Description("The production x ^= y is the same as x = x ^ y")]
        public void S11_13_2_A4_10_T2_4()
        {
            RunFile(@"S11.13.2_A4.10_T2.4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.2")]
        [Description("The production x ^= y is the same as x = x ^ y")]
        public void S11_13_2_A4_10_T2_5()
        {
            RunFile(@"S11.13.2_A4.10_T2.5.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.2")]
        [Description("The production x ^= y is the same as x = x ^ y")]
        public void S11_13_2_A4_10_T2_6()
        {
            RunFile(@"S11.13.2_A4.10_T2.6.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.2")]
        [Description("The production x ^= y is the same as x = x ^ y")]
        public void S11_13_2_A4_10_T2_7()
        {
            RunFile(@"S11.13.2_A4.10_T2.7.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.2")]
        [Description("The production x ^= y is the same as x = x ^ y")]
        public void S11_13_2_A4_10_T2_8()
        {
            RunFile(@"S11.13.2_A4.10_T2.8.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.2")]
        [Description("The production x ^= y is the same as x = x ^ y")]
        public void S11_13_2_A4_10_T2_9()
        {
            RunFile(@"S11.13.2_A4.10_T2.9.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.3")]
        [Description("The production x |= y is the same as x = x | y")]
        public void S11_13_2_A4_11_T1_1()
        {
            RunFile(@"S11.13.2_A4.11_T1.1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.3")]
        [Description("The production x |= y is the same as x = x | y")]
        public void S11_13_2_A4_11_T1_2()
        {
            RunFile(@"S11.13.2_A4.11_T1.2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.3")]
        [Description("The production x |= y is the same as x = x | y")]
        public void S11_13_2_A4_11_T1_3()
        {
            RunFile(@"S11.13.2_A4.11_T1.3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.3")]
        [Description("The production x |= y is the same as x = x | y")]
        public void S11_13_2_A4_11_T1_4()
        {
            RunFile(@"S11.13.2_A4.11_T1.4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.3")]
        [Description("The production x |= y is the same as x = x | y")]
        public void S11_13_2_A4_11_T2_1()
        {
            RunFile(@"S11.13.2_A4.11_T2.1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.3")]
        [Description("The production x |= y is the same as x = x | y")]
        public void S11_13_2_A4_11_T2_2()
        {
            RunFile(@"S11.13.2_A4.11_T2.2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.3")]
        [Description("The production x |= y is the same as x = x | y")]
        public void S11_13_2_A4_11_T2_3()
        {
            RunFile(@"S11.13.2_A4.11_T2.3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.3")]
        [Description("The production x |= y is the same as x = x | y")]
        public void S11_13_2_A4_11_T2_4()
        {
            RunFile(@"S11.13.2_A4.11_T2.4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.3")]
        [Description("The production x |= y is the same as x = x | y")]
        public void S11_13_2_A4_11_T2_5()
        {
            RunFile(@"S11.13.2_A4.11_T2.5.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.3")]
        [Description("The production x |= y is the same as x = x | y")]
        public void S11_13_2_A4_11_T2_6()
        {
            RunFile(@"S11.13.2_A4.11_T2.6.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.3")]
        [Description("The production x |= y is the same as x = x | y")]
        public void S11_13_2_A4_11_T2_7()
        {
            RunFile(@"S11.13.2_A4.11_T2.7.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.3")]
        [Description("The production x |= y is the same as x = x | y")]
        public void S11_13_2_A4_11_T2_8()
        {
            RunFile(@"S11.13.2_A4.11_T2.8.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.3")]
        [Description("The production x |= y is the same as x = x | y")]
        public void S11_13_2_A4_11_T2_9()
        {
            RunFile(@"S11.13.2_A4.11_T2.9.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.2")]
        [Description("The production x /= y is the same as x = x / y")]
        public void S11_13_2_A4_2_T1_1()
        {
            RunFile(@"S11.13.2_A4.2_T1.1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.2")]
        [Description("The production x /= y is the same as x = x / y")]
        public void S11_13_2_A4_2_T1_2()
        {
            RunFile(@"S11.13.2_A4.2_T1.2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.2")]
        [Description("The production x /= y is the same as x = x / y")]
        public void S11_13_2_A4_2_T1_3()
        {
            RunFile(@"S11.13.2_A4.2_T1.3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.2")]
        [Description("The production x /= y is the same as x = x / y")]
        public void S11_13_2_A4_2_T1_4()
        {
            RunFile(@"S11.13.2_A4.2_T1.4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.2")]
        [Description("The production x /= y is the same as x = x / y")]
        public void S11_13_2_A4_2_T2_1()
        {
            RunFile(@"S11.13.2_A4.2_T2.1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.2")]
        [Description("The production x /= y is the same as x = x / y")]
        public void S11_13_2_A4_2_T2_2()
        {
            RunFile(@"S11.13.2_A4.2_T2.2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.2")]
        [Description("The production x /= y is the same as x = x / y")]
        public void S11_13_2_A4_2_T2_3()
        {
            RunFile(@"S11.13.2_A4.2_T2.3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.2")]
        [Description("The production x /= y is the same as x = x / y")]
        public void S11_13_2_A4_2_T2_4()
        {
            RunFile(@"S11.13.2_A4.2_T2.4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.2")]
        [Description("The production x /= y is the same as x = x / y")]
        public void S11_13_2_A4_2_T2_5()
        {
            RunFile(@"S11.13.2_A4.2_T2.5.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.2")]
        [Description("The production x /= y is the same as x = x / y")]
        public void S11_13_2_A4_2_T2_6()
        {
            RunFile(@"S11.13.2_A4.2_T2.6.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.2")]
        [Description("The production x /= y is the same as x = x / y")]
        public void S11_13_2_A4_2_T2_7()
        {
            RunFile(@"S11.13.2_A4.2_T2.7.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.2")]
        [Description("The production x /= y is the same as x = x / y")]
        public void S11_13_2_A4_2_T2_8()
        {
            RunFile(@"S11.13.2_A4.2_T2.8.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.2")]
        [Description("The production x /= y is the same as x = x / y")]
        public void S11_13_2_A4_2_T2_9()
        {
            RunFile(@"S11.13.2_A4.2_T2.9.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.3")]
        [Description("The production x %= y is the same as x = x % y")]
        public void S11_13_2_A4_3_T1_1()
        {
            RunFile(@"S11.13.2_A4.3_T1.1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.3")]
        [Description("The production x %= y is the same as x = x % y")]
        public void S11_13_2_A4_3_T1_2()
        {
            RunFile(@"S11.13.2_A4.3_T1.2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.3")]
        [Description("The production x %= y is the same as x = x % y")]
        public void S11_13_2_A4_3_T1_3()
        {
            RunFile(@"S11.13.2_A4.3_T1.3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.3")]
        [Description("The production x %= y is the same as x = x % y")]
        public void S11_13_2_A4_3_T1_4()
        {
            RunFile(@"S11.13.2_A4.3_T1.4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.3")]
        [Description("The production x %= y is the same as x = x % y")]
        public void S11_13_2_A4_3_T2_1()
        {
            RunFile(@"S11.13.2_A4.3_T2.1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.3")]
        [Description("The production x %= y is the same as x = x % y")]
        public void S11_13_2_A4_3_T2_2()
        {
            RunFile(@"S11.13.2_A4.3_T2.2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.3")]
        [Description("The production x %= y is the same as x = x % y")]
        public void S11_13_2_A4_3_T2_3()
        {
            RunFile(@"S11.13.2_A4.3_T2.3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.3")]
        [Description("The production x %= y is the same as x = x % y")]
        public void S11_13_2_A4_3_T2_4()
        {
            RunFile(@"S11.13.2_A4.3_T2.4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.3")]
        [Description("The production x %= y is the same as x = x % y")]
        public void S11_13_2_A4_3_T2_5()
        {
            RunFile(@"S11.13.2_A4.3_T2.5.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.3")]
        [Description("The production x %= y is the same as x = x % y")]
        public void S11_13_2_A4_3_T2_6()
        {
            RunFile(@"S11.13.2_A4.3_T2.6.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.3")]
        [Description("The production x %= y is the same as x = x % y")]
        public void S11_13_2_A4_3_T2_7()
        {
            RunFile(@"S11.13.2_A4.3_T2.7.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.3")]
        [Description("The production x %= y is the same as x = x % y")]
        public void S11_13_2_A4_3_T2_8()
        {
            RunFile(@"S11.13.2_A4.3_T2.8.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.5.3")]
        [Description("The production x %= y is the same as x = x % y")]
        public void S11_13_2_A4_3_T2_9()
        {
            RunFile(@"S11.13.2_A4.3_T2.9.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.6.1")]
        [Description("The production x += y is the same as x = x + y")]
        public void S11_13_2_A4_4_T1_1()
        {
            RunFile(@"S11.13.2_A4.4_T1.1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.6.1")]
        [Description("The production x += y is the same as x = x + y")]
        public void S11_13_2_A4_4_T1_2()
        {
            RunFile(@"S11.13.2_A4.4_T1.2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.6.1")]
        [Description("The production x += y is the same as x = x + y")]
        public void S11_13_2_A4_4_T1_3()
        {
            RunFile(@"S11.13.2_A4.4_T1.3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.6.1")]
        [Description("The production x += y is the same as x = x + y")]
        public void S11_13_2_A4_4_T1_4()
        {
            RunFile(@"S11.13.2_A4.4_T1.4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.6.1")]
        [Description("The production x += y is the same as x = x + y")]
        public void S11_13_2_A4_4_T2_1()
        {
            RunFile(@"S11.13.2_A4.4_T2.1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.6.1")]
        [Description("The production x += y is the same as x = x + y")]
        public void S11_13_2_A4_4_T2_2()
        {
            RunFile(@"S11.13.2_A4.4_T2.2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.6.1")]
        [Description("The production x += y is the same as x = x + y")]
        public void S11_13_2_A4_4_T2_3()
        {
            RunFile(@"S11.13.2_A4.4_T2.3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.6.1")]
        [Description("The production x += y is the same as x = x + y")]
        public void S11_13_2_A4_4_T2_4()
        {
            RunFile(@"S11.13.2_A4.4_T2.4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.6.1")]
        [Description("The production x += y is the same as x = x + y")]
        public void S11_13_2_A4_4_T2_5()
        {
            RunFile(@"S11.13.2_A4.4_T2.5.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.6.1")]
        [Description("The production x += y is the same as x = x + y")]
        public void S11_13_2_A4_4_T2_6()
        {
            RunFile(@"S11.13.2_A4.4_T2.6.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.6.1")]
        [Description("The production x += y is the same as x = x + y")]
        public void S11_13_2_A4_4_T2_7()
        {
            RunFile(@"S11.13.2_A4.4_T2.7.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.6.1")]
        [Description("The production x += y is the same as x = x + y")]
        public void S11_13_2_A4_4_T2_8()
        {
            RunFile(@"S11.13.2_A4.4_T2.8.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.6.1")]
        [Description("The production x += y is the same as x = x + y")]
        public void S11_13_2_A4_4_T2_9()
        {
            RunFile(@"S11.13.2_A4.4_T2.9.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.6.2")]
        [Description("The production x -= y is the same as x = x - y")]
        public void S11_13_2_A4_5_T1_1()
        {
            RunFile(@"S11.13.2_A4.5_T1.1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.6.2")]
        [Description("The production x -= y is the same as x = x - y")]
        public void S11_13_2_A4_5_T1_2()
        {
            RunFile(@"S11.13.2_A4.5_T1.2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.6.2")]
        [Description("The production x -= y is the same as x = x - y")]
        public void S11_13_2_A4_5_T1_3()
        {
            RunFile(@"S11.13.2_A4.5_T1.3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.6.2")]
        [Description("The production x -= y is the same as x = x - y")]
        public void S11_13_2_A4_5_T1_4()
        {
            RunFile(@"S11.13.2_A4.5_T1.4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.6.2")]
        [Description("The production x -= y is the same as x = x - y")]
        public void S11_13_2_A4_5_T2_1()
        {
            RunFile(@"S11.13.2_A4.5_T2.1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.6.2")]
        [Description("The production x -= y is the same as x = x - y")]
        public void S11_13_2_A4_5_T2_2()
        {
            RunFile(@"S11.13.2_A4.5_T2.2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.6.2")]
        [Description("The production x -= y is the same as x = x - y")]
        public void S11_13_2_A4_5_T2_3()
        {
            RunFile(@"S11.13.2_A4.5_T2.3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.6.2")]
        [Description("The production x -= y is the same as x = x - y")]
        public void S11_13_2_A4_5_T2_4()
        {
            RunFile(@"S11.13.2_A4.5_T2.4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.6.2")]
        [Description("The production x -= y is the same as x = x - y")]
        public void S11_13_2_A4_5_T2_5()
        {
            RunFile(@"S11.13.2_A4.5_T2.5.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.6.2")]
        [Description("The production x -= y is the same as x = x - y")]
        public void S11_13_2_A4_5_T2_6()
        {
            RunFile(@"S11.13.2_A4.5_T2.6.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.6.2")]
        [Description("The production x -= y is the same as x = x - y")]
        public void S11_13_2_A4_5_T2_7()
        {
            RunFile(@"S11.13.2_A4.5_T2.7.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.6.2")]
        [Description("The production x -= y is the same as x = x - y")]
        public void S11_13_2_A4_5_T2_8()
        {
            RunFile(@"S11.13.2_A4.5_T2.8.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.6.2")]
        [Description("The production x -= y is the same as x = x - y")]
        public void S11_13_2_A4_5_T2_9()
        {
            RunFile(@"S11.13.2_A4.5_T2.9.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.1")]
        [Description("The production x <<= y is the same as x = x << y")]
        public void S11_13_2_A4_6_T1_1()
        {
            RunFile(@"S11.13.2_A4.6_T1.1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.1")]
        [Description("The production x <<= y is the same as x = x << y")]
        public void S11_13_2_A4_6_T1_2()
        {
            RunFile(@"S11.13.2_A4.6_T1.2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.1")]
        [Description("The production x <<= y is the same as x = x << y")]
        public void S11_13_2_A4_6_T1_3()
        {
            RunFile(@"S11.13.2_A4.6_T1.3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.1")]
        [Description("The production x <<= y is the same as x = x << y")]
        public void S11_13_2_A4_6_T1_4()
        {
            RunFile(@"S11.13.2_A4.6_T1.4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.1")]
        [Description("The production x <<= y is the same as x = x << y")]
        public void S11_13_2_A4_6_T2_1()
        {
            RunFile(@"S11.13.2_A4.6_T2.1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.1")]
        [Description("The production x <<= y is the same as x = x << y")]
        public void S11_13_2_A4_6_T2_2()
        {
            RunFile(@"S11.13.2_A4.6_T2.2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.1")]
        [Description("The production x <<= y is the same as x = x << y")]
        public void S11_13_2_A4_6_T2_3()
        {
            RunFile(@"S11.13.2_A4.6_T2.3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.1")]
        [Description("The production x <<= y is the same as x = x << y")]
        public void S11_13_2_A4_6_T2_4()
        {
            RunFile(@"S11.13.2_A4.6_T2.4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.1")]
        [Description("The production x <<= y is the same as x = x << y")]
        public void S11_13_2_A4_6_T2_5()
        {
            RunFile(@"S11.13.2_A4.6_T2.5.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.1")]
        [Description("The production x <<= y is the same as x = x << y")]
        public void S11_13_2_A4_6_T2_6()
        {
            RunFile(@"S11.13.2_A4.6_T2.6.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.1")]
        [Description("The production x <<= y is the same as x = x << y")]
        public void S11_13_2_A4_6_T2_7()
        {
            RunFile(@"S11.13.2_A4.6_T2.7.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.1")]
        [Description("The production x <<= y is the same as x = x << y")]
        public void S11_13_2_A4_6_T2_8()
        {
            RunFile(@"S11.13.2_A4.6_T2.8.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.1")]
        [Description("The production x <<= y is the same as x = x << y")]
        public void S11_13_2_A4_6_T2_9()
        {
            RunFile(@"S11.13.2_A4.6_T2.9.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.2")]
        [Description("The production x >>= y is the same as x = x >> y")]
        public void S11_13_2_A4_7_T1_1()
        {
            RunFile(@"S11.13.2_A4.7_T1.1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.2")]
        [Description("The production x >>= y is the same as x = x >> y")]
        public void S11_13_2_A4_7_T1_2()
        {
            RunFile(@"S11.13.2_A4.7_T1.2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.2")]
        [Description("The production x >>= y is the same as x = x >> y")]
        public void S11_13_2_A4_7_T1_3()
        {
            RunFile(@"S11.13.2_A4.7_T1.3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.2")]
        [Description("The production x >>= y is the same as x = x >> y")]
        public void S11_13_2_A4_7_T1_4()
        {
            RunFile(@"S11.13.2_A4.7_T1.4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.2")]
        [Description("The production x >>= y is the same as x = x >> y")]
        public void S11_13_2_A4_7_T2_1()
        {
            RunFile(@"S11.13.2_A4.7_T2.1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.2")]
        [Description("The production x >>= y is the same as x = x >> y")]
        public void S11_13_2_A4_7_T2_2()
        {
            RunFile(@"S11.13.2_A4.7_T2.2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.2")]
        [Description("The production x >>= y is the same as x = x >> y")]
        public void S11_13_2_A4_7_T2_3()
        {
            RunFile(@"S11.13.2_A4.7_T2.3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.2")]
        [Description("The production x >>= y is the same as x = x >> y")]
        public void S11_13_2_A4_7_T2_4()
        {
            RunFile(@"S11.13.2_A4.7_T2.4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.2")]
        [Description("The production x >>= y is the same as x = x >> y")]
        public void S11_13_2_A4_7_T2_5()
        {
            RunFile(@"S11.13.2_A4.7_T2.5.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.2")]
        [Description("The production x >>= y is the same as x = x >> y")]
        public void S11_13_2_A4_7_T2_6()
        {
            RunFile(@"S11.13.2_A4.7_T2.6.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.2")]
        [Description("The production x >>= y is the same as x = x >> y")]
        public void S11_13_2_A4_7_T2_7()
        {
            RunFile(@"S11.13.2_A4.7_T2.7.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.2")]
        [Description("The production x >>= y is the same as x = x >> y")]
        public void S11_13_2_A4_7_T2_8()
        {
            RunFile(@"S11.13.2_A4.7_T2.8.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.2")]
        [Description("The production x >>= y is the same as x = x >> y")]
        public void S11_13_2_A4_7_T2_9()
        {
            RunFile(@"S11.13.2_A4.7_T2.9.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.3")]
        [Description("The production x >>>= y is the same as x = x >>> y")]
        public void S11_13_2_A4_8_T1_1()
        {
            RunFile(@"S11.13.2_A4.8_T1.1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.3")]
        [Description("The production x >>>= y is the same as x = x >>> y")]
        public void S11_13_2_A4_8_T1_2()
        {
            RunFile(@"S11.13.2_A4.8_T1.2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.3")]
        [Description("The production x >>>= y is the same as x = x >>> y")]
        public void S11_13_2_A4_8_T1_3()
        {
            RunFile(@"S11.13.2_A4.8_T1.3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.3")]
        [Description("The production x >>>= y is the same as x = x >>> y")]
        public void S11_13_2_A4_8_T1_4()
        {
            RunFile(@"S11.13.2_A4.8_T1.4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.3")]
        [Description("The production x >>>= y is the same as x = x >>> y")]
        public void S11_13_2_A4_8_T2_1()
        {
            RunFile(@"S11.13.2_A4.8_T2.1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.3")]
        [Description("The production x >>>= y is the same as x = x >>> y")]
        public void S11_13_2_A4_8_T2_2()
        {
            RunFile(@"S11.13.2_A4.8_T2.2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.3")]
        [Description("The production x >>>= y is the same as x = x >>> y")]
        public void S11_13_2_A4_8_T2_3()
        {
            RunFile(@"S11.13.2_A4.8_T2.3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.3")]
        [Description("The production x >>>= y is the same as x = x >>> y")]
        public void S11_13_2_A4_8_T2_4()
        {
            RunFile(@"S11.13.2_A4.8_T2.4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.3")]
        [Description("The production x >>>= y is the same as x = x >>> y")]
        public void S11_13_2_A4_8_T2_5()
        {
            RunFile(@"S11.13.2_A4.8_T2.5.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.3")]
        [Description("The production x >>>= y is the same as x = x >>> y")]
        public void S11_13_2_A4_8_T2_6()
        {
            RunFile(@"S11.13.2_A4.8_T2.6.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.3")]
        [Description("The production x >>>= y is the same as x = x >>> y")]
        public void S11_13_2_A4_8_T2_7()
        {
            RunFile(@"S11.13.2_A4.8_T2.7.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.3")]
        [Description("The production x >>>= y is the same as x = x >>> y")]
        public void S11_13_2_A4_8_T2_8()
        {
            RunFile(@"S11.13.2_A4.8_T2.8.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.7.3")]
        [Description("The production x >>>= y is the same as x = x >>> y")]
        public void S11_13_2_A4_8_T2_9()
        {
            RunFile(@"S11.13.2_A4.8_T2.9.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.1")]
        [Description("The production x &= y is the same as x = x & y")]
        public void S11_13_2_A4_9_T1_1()
        {
            RunFile(@"S11.13.2_A4.9_T1.1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.1")]
        [Description("The production x &= y is the same as x = x & y")]
        public void S11_13_2_A4_9_T1_2()
        {
            RunFile(@"S11.13.2_A4.9_T1.2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.1")]
        [Description("The production x &= y is the same as x = x & y")]
        public void S11_13_2_A4_9_T1_3()
        {
            RunFile(@"S11.13.2_A4.9_T1.3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.1")]
        [Description("The production x &= y is the same as x = x & y")]
        public void S11_13_2_A4_9_T1_4()
        {
            RunFile(@"S11.13.2_A4.9_T1.4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.1")]
        [Description("The production x &= y is the same as x = x & y")]
        public void S11_13_2_A4_9_T2_1()
        {
            RunFile(@"S11.13.2_A4.9_T2.1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.1")]
        [Description("The production x &= y is the same as x = x & y")]
        public void S11_13_2_A4_9_T2_2()
        {
            RunFile(@"S11.13.2_A4.9_T2.2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.1")]
        [Description("The production x &= y is the same as x = x & y")]
        public void S11_13_2_A4_9_T2_3()
        {
            RunFile(@"S11.13.2_A4.9_T2.3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.1")]
        [Description("The production x &= y is the same as x = x & y")]
        public void S11_13_2_A4_9_T2_4()
        {
            RunFile(@"S11.13.2_A4.9_T2.4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.1")]
        [Description("The production x &= y is the same as x = x & y")]
        public void S11_13_2_A4_9_T2_5()
        {
            RunFile(@"S11.13.2_A4.9_T2.5.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.1")]
        [Description("The production x &= y is the same as x = x & y")]
        public void S11_13_2_A4_9_T2_6()
        {
            RunFile(@"S11.13.2_A4.9_T2.6.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.1")]
        [Description("The production x &= y is the same as x = x & y")]
        public void S11_13_2_A4_9_T2_7()
        {
            RunFile(@"S11.13.2_A4.9_T2.7.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.1")]
        [Description("The production x &= y is the same as x = x & y")]
        public void S11_13_2_A4_9_T2_8()
        {
            RunFile(@"S11.13.2_A4.9_T2.8.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.13.2")]
        [TestCategory("ECMA 11.10.1")]
        [Description("The production x &= y is the same as x = x & y")]
        public void S11_13_2_A4_9_T2_9()
        {
            RunFile(@"S11.13.2_A4.9_T2.9.js");
        }
    }
}