// <auto-generated />
namespace IronJS.Tests.UnitTests.IE9.chapter15._15_7._15_7_3
{
    using System;
    using NUnit.Framework;

    [TestFixture]
    public class _15_7_3_1_Tests : IE9TestFixture
    {
        public _15_7_3_1_Tests() : base(@"chapter15\15.7\15.7.3\15.7.3.1") { }

        [Test(Description = "Number.prototype is a data property with default attribute values (false)")] public void _15_7_3_1__1() { RunFile(@"15.7.3.1-1.js"); }
        [Test(Description = "Number.prototype, initial value is the Number prototype object")] public void _15_7_3_1__2() { RunFile(@"15.7.3.1-2.js"); }
    }
}