// <auto-generated />
namespace IronJS.Tests.UnitTests.Sputnik.Conformance.NativeECMAScriptObjects.NumberObjects.PropertiesOfNumberConstructor
{
    using System;
    using Microsoft.VisualStudio.TestTools.UnitTesting;

    [TestClass]
    public class NumberMAXVALUETests : SputnikTestFixture
    {
        public NumberMAXVALUETests()
            : base(@"Conformance\15_Native_ECMA_Script_Objects\15.7_Number_Objects\15.7.3_Properties_of_Number_Constructor\15.7.3.2_Number.MAX_VALUE")
        {
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.7.3.2")]
        [Description("Number.MAX_VALUE is approximately 1.7976931348623157e308")]
        public void S15_7_3_2_A1()
        {
            RunFile(@"S15.7.3.2_A1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.7.3.2")]
        [Description("Number.MAX_VALUE is ReadOnly")]
        public void S15_7_3_2_A2()
        {
            RunFile(@"S15.7.3.2_A2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.7.3.2")]
        [Description("Number.MAX_VALUE is DontDelete")]
        public void S15_7_3_2_A3()
        {
            RunFile(@"S15.7.3.2_A3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.7.3.2")]
        [Description("Number.MAX_VALUE has the attribute DontEnum")]
        public void S15_7_3_2_A4()
        {
            RunFile(@"S15.7.3.2_A4.js");
        }
    }
}