// <auto-generated />
namespace IronJS.Tests.UnitTests.Sputnik.Conformance.NativeECMAScriptObjects.ErrorObjects
{
    using System;
    using Microsoft.VisualStudio.TestTools.UnitTesting;

    [TestClass]
    public class PropertiesOfTheErrorConstructorTests : SputnikTestFixture
    {
        public PropertiesOfTheErrorConstructorTests()
            : base(@"Conformance\15_Native_ECMA_Script_Objects\15.11_Error_Objects\15.11.3_Properties_of_the_Error_Constructor")
        {
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.11.3.1")]
        [TestCategory("ECMA 16")]
        [Description("Error.prototype property has the attributes {DontDelete}")]
        public void S15_11_3_1_A1_T1()
        {
            RunFile(@"S15.11.3.1_A1_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.11.3.1")]
        [TestCategory("ECMA 16")]
        [Description("Error.prototype property has the attributes {DontEnum}")]
        public void S15_11_3_1_A2_T1()
        {
            RunFile(@"S15.11.3.1_A2_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.11.3.1")]
        [TestCategory("ECMA 16")]
        [Description("Error.prototype property has the attributes {ReadOnly}")]
        public void S15_11_3_1_A3_T1()
        {
            RunFile(@"S15.11.3.1_A3_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.11.3.1")]
        [TestCategory("ECMA 16")]
        [Description("The Error has property prototype")]
        public void S15_11_3_1_A4_T1()
        {
            RunFile(@"S15.11.3.1_A4_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.11.3")]
        [TestCategory("ECMA 16")]
        [Description("The value of the internal [[Prototype]] property of the Error constructor is the Function prototype object(15.3.4)")]
        public void S15_11_3_A1_T1()
        {
            RunFile(@"S15.11.3_A1_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.11.3")]
        [TestCategory("ECMA 16")]
        [Description("The length property value is 1")]
        public void S15_11_3_A2_T1()
        {
            RunFile(@"S15.11.3_A2_T1.js");
        }
    }
}