// <auto-generated />
namespace IronJS.Tests.UnitTests.Sputnik.Conformance.Statement
{
    using System;
    using Microsoft.VisualStudio.TestTools.UnitTesting;

    [TestClass]
    public class TheThrowStatementTests : SputnikTestFixture
    {
        public TheThrowStatementTests()
            : base(@"Conformance\12_Statement\12.13_The_throw_statement")
        {
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 12.13")]
        [Description("Sanity test for throw statement")]
        public void S12_13_A1()
        {
            RunFile_ExpectException(@"S12.13_A1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 12.13")]
        [Description("\"throw Expression\" returns (throw, GetValue(Result(1)), empty), where 1 evaluates Expression")]
        public void S12_13_A2_T1()
        {
            RunFile(@"S12.13_A2_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 12.13")]
        [Description("\"throw Expression\" returns (throw, GetValue(Result(1)), empty), where 1 evaluates Expression")]
        public void S12_13_A2_T2()
        {
            RunFile(@"S12.13_A2_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 12.13")]
        [Description("\"throw Expression\" returns (throw, GetValue(Result(1)), empty), where 1 evaluates Expression")]
        public void S12_13_A2_T3()
        {
            RunFile(@"S12.13_A2_T3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 12.13")]
        [Description("\"throw Expression\" returns (throw, GetValue(Result(1)), empty), where 1 evaluates Expression")]
        public void S12_13_A2_T4()
        {
            RunFile(@"S12.13_A2_T4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 12.13")]
        [Description("\"throw Expression\" returns (throw, GetValue(Result(1)), empty), where 1 evaluates Expression")]
        public void S12_13_A2_T5()
        {
            RunFile(@"S12.13_A2_T5.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 12.13")]
        [Description("\"throw Expression\" returns (throw, GetValue(Result(1)), empty), where 1 evaluates Expression")]
        public void S12_13_A2_T6()
        {
            RunFile(@"S12.13_A2_T6.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 12.13")]
        [Description("\"throw Expression\" returns (throw, GetValue(Result(1)), empty), where 1 evaluates Expression")]
        public void S12_13_A2_T7()
        {
            RunFile(@"S12.13_A2_T7.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 12.13")]
        [Description("1. Evaluate Expression")]
        public void S12_13_A3_T1()
        {
            RunFile(@"S12.13_A3_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 12.13")]
        [Description("1. Evaluate Expression")]
        public void S12_13_A3_T2()
        {
            RunFile(@"S12.13_A3_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 12.13")]
        [Description("1. Evaluate Expression")]
        public void S12_13_A3_T3()
        {
            RunFile(@"S12.13_A3_T3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 12.13")]
        [Description("1. Evaluate Expression")]
        public void S12_13_A3_T4()
        {
            RunFile(@"S12.13_A3_T4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 12.13")]
        [Description("1. Evaluate Expression")]
        public void S12_13_A3_T5()
        {
            RunFile(@"S12.13_A3_T5.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 12.13")]
        [Description("1. Evaluate Expression")]
        public void S12_13_A3_T6()
        {
            RunFile(@"S12.13_A3_T6.js");
        }
    }
}