// <auto-generated />
namespace IronJS.Tests.UnitTests.Sputnik.Conformance.NativeECMAScriptObjects.NumberObjects
{
    using System;
    using NUnit.Framework;

    [TestFixture]
    public class PropertiesOfNumberInstancesTests : SputnikTestFixture
    {
        public PropertiesOfNumberInstancesTests()
            : base(@"Conformance\15_Native_ECMA_Script_Objects\15.7_Number_Objects\15.7.5_Properties_of_Number_Instances")
        {
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.7.5")]
        [TestCase("S15.7.5_A1_T01.js", Description = "Number instances have no special properties beyond those inherited from the Number prototype object")]
        [TestCase("S15.7.5_A1_T02.js", Description = "Number instances have no special properties beyond those inherited from the Number prototype object")]
        [TestCase("S15.7.5_A1_T03.js", Description = "Number instances have no special properties beyond those inherited from the Number prototype object")]
        [TestCase("S15.7.5_A1_T04.js", Description = "Number instances have no special properties beyond those inherited from the Number prototype object")]
        [TestCase("S15.7.5_A1_T05.js", Description = "Number instances have no special properties beyond those inherited from the Number prototype object")]
        [TestCase("S15.7.5_A1_T06.js", Description = "Number instances have no special properties beyond those inherited from the Number prototype object")]
        [TestCase("S15.7.5_A1_T07.js", Description = "Number instances have no special properties beyond those inherited from the Number prototype object")]
        public void NumberInstancesHaveNoSpecialPropertiesBeyondThoseInheritedFromTheNumberPrototypeObject(string file)
        {
            RunFile(file);
        }
    }
}