// <auto-generated />
namespace IronJS.Tests.UnitTests.Sputnik.Conformance.NativeECMAScriptObjects.NumberObjects
{
    using System;
    using Microsoft.VisualStudio.TestTools.UnitTesting;

    [TestClass]
    public class TheNumberConstructorCalledAsAFunctionTests : SputnikTestFixture
    {
        public TheNumberConstructorCalledAsAFunctionTests()
            : base(@"Conformance\15_Native_ECMA_Script_Objects\15.7_Number_Objects\15.7.1_The_Number_Constructor_Called_as_a_Function")
        {
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.7.1.1")]
        [Description("Number([value]) returns a number value (not a Number object) computed by ToNumber(value) if value was supplied")]
        public void S15_7_1_1_A1()
        {
            RunFile(@"S15.7.1.1_A1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.7.1.1")]
        [Description("Number() returns +0")]
        public void S15_7_1_1_A2()
        {
            RunFile(@"S15.7.1.1_A2.js");
        }
    }
}