// <auto-generated />
namespace IronJS.Tests.UnitTests.Sputnik.Conformance.TypeConversion
{
    using System;
    using Microsoft.VisualStudio.TestTools.UnitTesting;

    [TestClass]
    public class ToBooleanTests : SputnikTestFixture
    {
        public ToBooleanTests()
            : base(@"Conformance\09_Type_Conversion\9.2_ToBoolean")
        {
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 9.2")]
        [TestCategory("ECMA 15.6.1")]
        [Description("Result of boolean conversion from undefined value is false")]
        public void S9_2_A1_T1()
        {
            RunFile(@"S9.2_A1_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 9.2")]
        [TestCategory("ECMA 11.4.9")]
        [Description("Result of boolean conversion from undefined value is false")]
        public void S9_2_A1_T2()
        {
            RunFile(@"S9.2_A1_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 9.2")]
        [TestCategory("ECMA 15.6.1")]
        [Description("Result of boolean conversion from null value is false")]
        public void S9_2_A2_T1()
        {
            RunFile(@"S9.2_A2_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 9.2")]
        [TestCategory("ECMA 11.4.9")]
        [Description("Result of boolean conversion from null value is false")]
        public void S9_2_A2_T2()
        {
            RunFile(@"S9.2_A2_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 9.2")]
        [TestCategory("ECMA 15.6.1")]
        [Description("Result of boolean conversion from boolean value is no conversion")]
        public void S9_2_A3_T1()
        {
            RunFile(@"S9.2_A3_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 9.2")]
        [TestCategory("ECMA 11.4.9")]
        [Description("Result of boolean conversion from boolean value is no conversion")]
        public void S9_2_A3_T2()
        {
            RunFile(@"S9.2_A3_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 9.2")]
        [TestCategory("ECMA 15.6.1")]
        [Description("Result of boolean conversion from number value is false if the argument is +0, -0, or NaN")]
        public void S9_2_A4_T1()
        {
            RunFile(@"S9.2_A4_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 9.2")]
        [TestCategory("ECMA 11.4.9")]
        [Description("Result of boolean conversion from number value is false if the argument is +0, -0, or NaN")]
        public void S9_2_A4_T2()
        {
            RunFile(@"S9.2_A4_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 9.2")]
        [TestCategory("ECMA 15.6.1")]
        [Description("Result of boolean conversion from number value is false if the argument is +0, -0, or NaN")]
        public void S9_2_A4_T3()
        {
            RunFile(@"S9.2_A4_T3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 9.2")]
        [TestCategory("ECMA 11.4.9")]
        [Description("Result of boolean conversion from number value is false if the argument is +0, -0, or NaN")]
        public void S9_2_A4_T4()
        {
            RunFile(@"S9.2_A4_T4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 9.2")]
        [TestCategory("ECMA 15.6.1")]
        [Description("Result of boolean conversion from nonempty string value (length is not zero) is true")]
        public void S9_2_A5_T1()
        {
            RunFile(@"S9.2_A5_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 9.2")]
        [TestCategory("ECMA 11.4.9")]
        [Description("Result of boolean conversion from nonempty string value (length is not zero) is true")]
        public void S9_2_A5_T2()
        {
            RunFile(@"S9.2_A5_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 9.2")]
        [TestCategory("ECMA 15.6.1")]
        [Description("Result of boolean conversion from nonempty string value (length is not zero) is true")]
        public void S9_2_A5_T3()
        {
            RunFile(@"S9.2_A5_T3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 9.2")]
        [TestCategory("ECMA 11.4.9")]
        [Description("Result of boolean conversion from nonempty string value (length is not zero) is true")]
        public void S9_2_A5_T4()
        {
            RunFile(@"S9.2_A5_T4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 9.2")]
        [TestCategory("ECMA 15.6.1")]
        [Description("Result of boolean conversion from object is true")]
        public void S9_2_A6_T1()
        {
            RunFile(@"S9.2_A6_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 9.2")]
        [TestCategory("ECMA 11.4.9")]
        [Description("Result of boolean conversion from object is true")]
        public void S9_2_A6_T2()
        {
            RunFile(@"S9.2_A6_T2.js");
        }
    }
}