// <auto-generated />
namespace IronJS.Tests.UnitTests.Sputnik.Conformance.LexicalConventions.Literals
{
    using System;
    using Microsoft.VisualStudio.TestTools.UnitTesting;

    [TestClass]
    public class StringLiteralsTests : SputnikTestFixture
    {
        public StringLiteralsTests()
            : base(@"Conformance\07_Lexical_Conventions\7.8_Literals\7.8.4_String_Literals")
        {
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("StringLiteral :: \"DoubleStringCharacters_opt\"")]
        public void S7_8_4_A1_1_T1()
        {
            RunFile_ExpectException(@"S7.8.4_A1.1_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("StringLiteral :: \"DoubleStringCharacters_opt\"")]
        public void S7_8_4_A1_1_T2()
        {
            RunFile_ExpectException(@"S7.8.4_A1.1_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("StringLiteral :: \'SingleStringCharacters_opt\'")]
        public void S7_8_4_A1_2_T1()
        {
            RunFile_ExpectException(@"S7.8.4_A1.2_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("StringLiteral :: \'SingleStringCharacters_opt\'")]
        public void S7_8_4_A1_2_T2()
        {
            RunFile_ExpectException(@"S7.8.4_A1.2_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("Correct interpretation of ENGLISH ALPHABET")]
        public void S7_8_4_A2_1_T1()
        {
            RunFile(@"S7.8.4_A2.1_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("Correct interpretation of ENGLISH ALPHABET")]
        public void S7_8_4_A2_1_T2()
        {
            RunFile(@"S7.8.4_A2.1_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("Correct interpretation of RUSSIAN ALPHABET")]
        public void S7_8_4_A2_2_T1()
        {
            RunFile(@"S7.8.4_A2.2_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("Correct interpretation of RUSSIAN ALPHABET")]
        public void S7_8_4_A2_2_T2()
        {
            RunFile(@"S7.8.4_A2.2_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("Correct interpretation of DIGITS")]
        public void S7_8_4_A2_3_T1()
        {
            RunFile(@"S7.8.4_A2.3_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("StringLiteral :: \"\\\" or \'\\\' is not correct")]
        public void S7_8_4_A3_1_T1()
        {
            RunFile_ExpectException(@"S7.8.4_A3.1_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("StringLiteral :: \"\\\" or \'\\\' is not correct")]
        public void S7_8_4_A3_1_T2()
        {
            RunFile_ExpectException(@"S7.8.4_A3.1_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("StringLiteral :: \"\\\\\\\" or \'\\\\\\\' is not correct")]
        public void S7_8_4_A3_2_T1()
        {
            RunFile_ExpectException(@"S7.8.4_A3.2_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("StringLiteral :: \"\\\\\\\" or \'\\\\\\\' is not correct")]
        public void S7_8_4_A3_2_T2()
        {
            RunFile_ExpectException(@"S7.8.4_A3.2_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("CharacterEscapeSequnce :: SingleEscapeSequence")]
        public void S7_8_4_A4_1_T1()
        {
            RunFile(@"S7.8.4_A4.1_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("CharacterEscapeSequnce :: SingleEscapeSequence")]
        public void S7_8_4_A4_1_T2()
        {
            RunFile(@"S7.8.4_A4.1_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("CharacterEscapeSequnce :: NonEscapeSequence")]
        public void S7_8_4_A4_2_T1()
        {
            RunFile(@"S7.8.4_A4.2_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("CharacterEscapeSequnce :: NonEscapeSequence")]
        public void S7_8_4_A4_2_T2()
        {
            RunFile(@"S7.8.4_A4.2_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("CharacterEscapeSequnce :: NonEscapeSequence")]
        public void S7_8_4_A4_2_T3()
        {
            RunFile(@"S7.8.4_A4.2_T3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("CharacterEscapeSequnce :: NonEscapeSequence")]
        public void S7_8_4_A4_2_T4()
        {
            RunFile(@"S7.8.4_A4.2_T4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("CharacterEscapeSequnce :: NonEscapeSequence")]
        public void S7_8_4_A4_2_T5()
        {
            RunFile(@"S7.8.4_A4.2_T5.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("CharacterEscapeSequnce :: NonEscapeSequence")]
        public void S7_8_4_A4_2_T6()
        {
            RunFile(@"S7.8.4_A4.2_T6.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("CharacterEscapeSequnce :: NonEscapeSequence")]
        public void S7_8_4_A4_2_T7()
        {
            RunFile(@"S7.8.4_A4.2_T7.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("CharacterEscapeSequnce :: NonEscapeSequence")]
        public void S7_8_4_A4_2_T8()
        {
            RunFile(@"S7.8.4_A4.2_T8.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("NonEscapeSequence is not EscapeCharacter")]
        public void S7_8_4_A4_3_T1()
        {
            RunFile_ExpectException(@"S7.8.4_A4.3_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("NonEscapeSequence is not EscapeCharacter")]
        public void S7_8_4_A4_3_T2()
        {
            RunFile_ExpectException(@"S7.8.4_A4.3_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("NonEscapeSequence is not EscapeCharacter")]
        public void S7_8_4_A4_3_T3()
        {
            RunFile_ExpectException(@"S7.8.4_A4.3_T3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("NonEscapeSequence is not EscapeCharacter")]
        public void S7_8_4_A4_3_T4()
        {
            RunFile_ExpectException(@"S7.8.4_A4.3_T4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("NonEscapeSequence is not EscapeCharacter")]
        public void S7_8_4_A4_3_T5()
        {
            RunFile_ExpectException(@"S7.8.4_A4.3_T5.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("NonEscapeSequence is not EscapeCharacter")]
        public void S7_8_4_A4_3_T6()
        {
            RunFile_ExpectException(@"S7.8.4_A4.3_T6.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("NonEscapeSequence is not EscapeCharacter")]
        public void S7_8_4_A4_3_T7()
        {
            RunFile(@"S7.8.4_A4.3_T7.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("EscapeSequence :: 0")]
        public void S7_8_4_A5_1_T1()
        {
            RunFile(@"S7.8.4_A5.1_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("EscapeSequence :: 0")]
        public void S7_8_4_A5_1_T2()
        {
            RunFile(@"S7.8.4_A5.1_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("EscapeSequence :: 0")]
        public void S7_8_4_A5_1_T3()
        {
            RunFile(@"S7.8.4_A5.1_T3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("EscapeSequence :: HexEscapeSequence :: x HexDigit HexDigit")]
        public void S7_8_4_A6_1_T1()
        {
            RunFile(@"S7.8.4_A6.1_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("EscapeSequence :: HexEscapeSequence :: x HexDigit HexDigit")]
        public void S7_8_4_A6_1_T2()
        {
            RunFile(@"S7.8.4_A6.1_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("EscapeSequence :: HexEscapeSequence :: x HexDigit HexDigit")]
        public void S7_8_4_A6_1_T3()
        {
            RunFile(@"S7.8.4_A6.1_T3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("EscapeSequence :: HexEscapeSequence :: x HexDigit HexDigit")]
        public void S7_8_4_A6_1_T4()
        {
            RunFile_ExpectException(@"S7.8.4_A6.1_T4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("HexEscapeSequence :: x HexDigit is incorrect")]
        public void S7_8_4_A6_2_T1()
        {
            RunFile_ExpectException(@"S7.8.4_A6.2_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("HexEscapeSequence :: x HexDigit is incorrect")]
        public void S7_8_4_A6_2_T2()
        {
            RunFile_ExpectException(@"S7.8.4_A6.2_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("\\x HexDigit HexDigit SingleStringCharacter")]
        public void S7_8_4_A6_3_T1()
        {
            RunFile(@"S7.8.4_A6.3_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("HexEscapeSequence \\X HexDigit HexDigit is incorrect")]
        public void S7_8_4_A6_4_T1()
        {
            RunFile_ExpectException(@"S7.8.4_A6.4_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("HexEscapeSequence \\X HexDigit HexDigit is incorrect")]
        public void S7_8_4_A6_4_T2()
        {
            RunFile_ExpectException(@"S7.8.4_A6.4_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("EscapeSequence :: UnicodeEscapeSequence :: u HexDigit HexDigit HexDigit HexDigit")]
        public void S7_8_4_A7_1_T1()
        {
            RunFile(@"S7.8.4_A7.1_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("EscapeSequence :: UnicodeEscapeSequence :: u HexDigit HexDigit HexDigit HexDigit")]
        public void S7_8_4_A7_1_T2()
        {
            RunFile(@"S7.8.4_A7.1_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("EscapeSequence :: UnicodeEscapeSequence :: u HexDigit HexDigit HexDigit HexDigit")]
        public void S7_8_4_A7_1_T3()
        {
            RunFile(@"S7.8.4_A7.1_T3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("EscapeSequence :: UnicodeEscapeSequence :: u HexDigit HexDigit HexDigit HexDigit")]
        public void S7_8_4_A7_1_T4()
        {
            RunFile_ExpectException(@"S7.8.4_A7.1_T4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("UnicodeEscapeSequence :: u HexDigit (one, two or three time) is incorrect")]
        public void S7_8_4_A7_2_T1()
        {
            RunFile_ExpectException(@"S7.8.4_A7.2_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("UnicodeEscapeSequence :: u HexDigit (one, two or three time) is incorrect")]
        public void S7_8_4_A7_2_T2()
        {
            RunFile_ExpectException(@"S7.8.4_A7.2_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("UnicodeEscapeSequence :: u HexDigit (one, two or three time) is incorrect")]
        public void S7_8_4_A7_2_T3()
        {
            RunFile_ExpectException(@"S7.8.4_A7.2_T3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("UnicodeEscapeSequence :: u HexDigit (one, two or three time) is incorrect")]
        public void S7_8_4_A7_2_T4()
        {
            RunFile_ExpectException(@"S7.8.4_A7.2_T4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("UnicodeEscapeSequence :: u HexDigit (one, two or three time) is incorrect")]
        public void S7_8_4_A7_2_T5()
        {
            RunFile_ExpectException(@"S7.8.4_A7.2_T5.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("UnicodeEscapeSequence :: u HexDigit (one, two or three time) is incorrect")]
        public void S7_8_4_A7_2_T6()
        {
            RunFile_ExpectException(@"S7.8.4_A7.2_T6.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("\\u HexDigit HexDigit HexDigit HexDigit DoubleStringCharacter")]
        public void S7_8_4_A7_3_T1()
        {
            RunFile(@"S7.8.4_A7.3_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("UnicodeEscapeSequence \\U HexDigit HexDigit HexDigit HexDigit is incorrect")]
        public void S7_8_4_A7_4_T1()
        {
            RunFile_ExpectException(@"S7.8.4_A7.4_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 7.8.4")]
        [Description("UnicodeEscapeSequence \\U HexDigit HexDigit HexDigit HexDigit is incorrect")]
        public void S7_8_4_A7_4_T2()
        {
            RunFile_ExpectException(@"S7.8.4_A7.4_T2.js");
        }
    }
}