// <auto-generated />
namespace IronJS.Tests.UnitTests.IE9.chapter10._10_2._10_2_1._10_2_1_1
{
    using System;
    using NUnit.Framework;

    [TestFixture]
    public class _10_2_1_1_3_Tests : IE9TestFixture
    {
        public _10_2_1_1_3_Tests() : base(@"chapter10\10.2\10.2.1\10.2.1.1\10.2.1.1.3") { }

        [Test(Description = "Strict Mode - TypeError is thrown when changing the value of a Value Property of the Global Object under strict mode (NaN)")] public void _10_2_1_1_3__4__16__s() { RunFile(@"10.2.1.1.3-4-16-s.js"); }
        [Test(Description = "Strict Mode - TypeError is thrown when changing the value of a Value Property of the Global Object under strict mode (undefined)")] public void _10_2_1_1_3__4__18__s() { RunFile(@"10.2.1.1.3-4-18-s.js"); }
        [Test(Description = "Strict Mode - TypeError is not thrown when changing the value of the Constructor Properties of the Global Object under strict mode (Object)")] public void _10_2_1_1_3__4__22__s() { RunFile(@"10.2.1.1.3-4-22-s.js"); }
        [Test(Description = "Strict Mode - TypeError is not thrown when changing the value of the Constructor Properties of the Global Object under strict mode (Number)")] public void _10_2_1_1_3__4__27__s() { RunFile(@"10.2.1.1.3-4-27-s.js"); }
    }
}