// <auto-generated />
namespace IronJS.Tests.UnitTests.Sputnik.Conformance.NativeECMAScriptObjects.ObjectObjects.PropertiesOfTheObjectPrototypeObject
{
    using System;
    using Microsoft.VisualStudio.TestTools.UnitTesting;

    [TestClass]
    public class ObjectPrototypeToLocaleStringTests : SputnikTestFixture
    {
        public ObjectPrototypeToLocaleStringTests()
            : base(@"Conformance\15_Native_ECMA_Script_Objects\15.2_Object_Objects\15.2.4_Properties_of_the_Object_Prototype_Object\15.2.4.3_Object.prototype.toLocaleString")
        {
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.2.4.3")]
        [Description("toLocaleString function returns the result of calling toString()")]
        public void S15_2_4_3_A1()
        {
            RunFile(@"S15.2.4.3_A1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.2.4.3")]
        [Description("The Object.prototype.toLocaleString.length property has the attribute ReadOnly")]
        public void S15_2_4_3_A10()
        {
            RunFile(@"S15.2.4.3_A10.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.2.4.3")]
        [Description("The length property of the toLocaleString method is 0")]
        public void S15_2_4_3_A11()
        {
            RunFile(@"S15.2.4.3_A11.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.2.4.3")]
        [TestCategory("ECMA 13.2")]
        [Description("Object.prototype.toLocaleString has not prototype property")]
        public void S15_2_4_3_A6()
        {
            RunFile(@"S15.2.4.3_A6.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.2.4.3")]
        [TestCategory("ECMA 13.2")]
        [Description("Object.prototype.toLocaleString can\'t be used as a constructor")]
        public void S15_2_4_3_A7()
        {
            RunFile(@"S15.2.4.3_A7.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.2.4.3")]
        [Description("The Object.prototype.toLocaleString.length property has the attribute DontEnum")]
        public void S15_2_4_3_A8()
        {
            RunFile(@"S15.2.4.3_A8.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 15.2.4.3")]
        [Description("The Object.prototype.toLocaleString.length property has the attribute DontDelete")]
        public void S15_2_4_3_A9()
        {
            RunFile(@"S15.2.4.3_A9.js");
        }
    }
}