// <auto-generated />
namespace IronJS.Tests.UnitTests.IE9.chapter15._15_2._15_2_4
{
    using System;
    using NUnit.Framework;

    [TestFixture]
    public class _15_2_4_2_Tests : IE9TestFixture
    {
        public _15_2_4_2_Tests() : base(@"chapter15\15.2\15.2.4\15.2.4.2") { }

        [Test(Description = "Object.prototype.toString - \'[object Undefined]\' will be returned when \'this\' value is undefined")] public void _15_2_4_2__1__1() { RunFile(@"15.2.4.2-1-1.js"); }
        [Test(Description = "Object.prototype.toString - \'[object Undefined]\' will be returned when \'this\' value is undefined")] public void _15_2_4_2__1__2() { RunFile(@"15.2.4.2-1-2.js"); }
        [Test(Description = "Object.prototype.toString - \'[object Null]\' will be returned when \'this\' value is null")] public void _15_2_4_2__2__1() { RunFile(@"15.2.4.2-2-1.js"); }
        [Test(Description = "Object.prototype.toString - \'[object Null]\' will be returned when \'this\' value is null")] public void _15_2_4_2__2__2() { RunFile(@"15.2.4.2-2-2.js"); }
    }
}