// <auto-generated />
namespace IronJS.Tests.UnitTests.Sputnik.Conformance.Expressions.UnaryOperators
{
    using System;
    using Microsoft.VisualStudio.TestTools.UnitTesting;

    [TestClass]
    public class PrefixIncrementOperatorTests : SputnikTestFixture
    {
        public PrefixIncrementOperatorTests()
            : base(@"Conformance\11_Expressions\11.4_Unary_Operators\11.4.4_Prefix_Increment_Operator")
        {
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.4.4")]
        [TestCategory("ECMA 11.6.3")]
        [TestCategory("ECMA 7.2")]
        [TestCategory("ECMA 7.3")]
        [Description("White Space and Line Terminator between \"++\" and UnaryExpression are allowed")]
        public void S11_4_4_A1()
        {
            RunFile(@"S11.4.4_A1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.4.4")]
        [TestCategory("ECMA 11.6.3")]
        [Description("Operator ++x uses GetValue and PutValue")]
        public void S11_4_4_A2_1_T1()
        {
            RunFile(@"S11.4.4_A2.1_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.4.4")]
        [TestCategory("ECMA 11.6.3")]
        [Description("Operator ++x uses GetValue and PutValue")]
        public void S11_4_4_A2_1_T2()
        {
            RunFile(@"S11.4.4_A2.1_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.4.4")]
        [TestCategory("ECMA 11.6.3")]
        [Description("Operator ++x uses GetValue and PutValue")]
        public void S11_4_4_A2_1_T3()
        {
            RunFile_ExpectException(@"S11.4.4_A2.1_T3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.4.4")]
        [TestCategory("ECMA 8.6.2.6")]
        [Description("Operator ++x uses [[Default Value]]")]
        public void S11_4_4_A2_2_T1()
        {
            RunFile(@"S11.4.4_A2.2_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.4.4")]
        [TestCategory("ECMA 11.6.3")]
        [Description("Operator ++x returns x = ToNumber(x) + 1")]
        public void S11_4_4_A3_T1()
        {
            RunFile(@"S11.4.4_A3_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.4.4")]
        [TestCategory("ECMA 11.6.3")]
        [Description("Operator ++x returns x = ToNumber(x) + 1")]
        public void S11_4_4_A3_T2()
        {
            RunFile(@"S11.4.4_A3_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.4.4")]
        [TestCategory("ECMA 11.6.3")]
        [Description("Operator ++x returns x = ToNumber(x) + 1")]
        public void S11_4_4_A3_T3()
        {
            RunFile(@"S11.4.4_A3_T3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.4.4")]
        [TestCategory("ECMA 11.6.3")]
        [Description("Operator ++x returns x = ToNumber(x) + 1")]
        public void S11_4_4_A3_T4()
        {
            RunFile(@"S11.4.4_A3_T4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.4.4")]
        [TestCategory("ECMA 11.6.3")]
        [Description("Operator ++x returns x = ToNumber(x) + 1")]
        public void S11_4_4_A3_T5()
        {
            RunFile(@"S11.4.4_A3_T5.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.4.4")]
        [TestCategory("ECMA 11.6.3")]
        [Description("Operator ++x returns ToNumber(x) + 1")]
        public void S11_4_4_A4_T1()
        {
            RunFile(@"S11.4.4_A4_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.4.4")]
        [TestCategory("ECMA 11.6.3")]
        [Description("Operator ++x returns ToNumber(x) + 1")]
        public void S11_4_4_A4_T2()
        {
            RunFile(@"S11.4.4_A4_T2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.4.4")]
        [TestCategory("ECMA 11.6.3")]
        [Description("Operator ++x returns ToNumber(x) + 1")]
        public void S11_4_4_A4_T3()
        {
            RunFile(@"S11.4.4_A4_T3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.4.4")]
        [TestCategory("ECMA 11.6.3")]
        [Description("Operator ++x returns ToNumber(x) + 1")]
        public void S11_4_4_A4_T4()
        {
            RunFile(@"S11.4.4_A4_T4.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 11.4.4")]
        [TestCategory("ECMA 11.6.3")]
        [Description("Operator ++x returns ToNumber(x) + 1")]
        public void S11_4_4_A4_T5()
        {
            RunFile(@"S11.4.4_A4_T5.js");
        }
    }
}