// <auto-generated />
namespace IronJS.Tests.UnitTests.Sputnik.Conformance.NativeECMAScriptObjects.DateObjects.PropertiesOfTheDatePrototypeObject
{
    using System;
    using NUnit.Framework;

    [TestFixture]
    public class DatePrototypeGetMonthTests : SputnikTestFixture
    {
        public DatePrototypeGetMonthTests()
            : base(@"Conformance\15_Native_ECMA_Script_Objects\15.9_Date_Objects\15.9.5_Properties_of_the_Date_Prototype_Object\15.9.5.12_Date.prototype.getMonth")
        {
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5.12")]
        [TestCase("S15.9.5.12_A1_T1.js", Description = "The Date.prototype property \"getMonth\" has { DontEnum } attributes")]
        [TestCase("S15.9.5.12_A1_T2.js", Description = "The Date.prototype property \"getMonth\" has { DontEnum } attributes")]
        [TestCase("S15.9.5.12_A1_T3.js", Description = "The Date.prototype property \"getMonth\" has { DontEnum } attributes")]
        public void TheDatePrototypePropertyGetMonthHasDontEnumAttributes(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5.12")]
        [TestCase("S15.9.5.12_A2_T1.js", Description = "The \"length\" property of the \"getMonth\" is 0")]
        public void TheLengthPropertyOfTheGetMonthIs0(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5.12")]
        [TestCase("S15.9.5.12_A3_T1.js", Description = "The Date.prototype.getMonth property \"length\" has { ReadOnly, DontDelete, DontEnum } attributes")]
        [TestCase("S15.9.5.12_A3_T2.js", Description = "The Date.prototype.getMonth property \"length\" has { ReadOnly, DontDelete, DontEnum } attributes")]
        [TestCase("S15.9.5.12_A3_T3.js", Description = "The Date.prototype.getMonth property \"length\" has { ReadOnly, DontDelete, DontEnum } attributes")]
        public void TheDatePrototypeGetMonthPropertyLengthHasReadOnlyDontDeleteDontEnumAttributes(string file)
        {
            RunFile(file);
        }
    }
}