// <auto-generated />
namespace IronJS.Tests.UnitTests.Sputnik.Conformance.NativeECMAScriptObjects.DateObjects.PropertiesOfTheDatePrototypeObject
{
    using System;
    using NUnit.Framework;

    [TestFixture]
    public class DatePrototypeSetUTCFullYearTests : SputnikTestFixture
    {
        public DatePrototypeSetUTCFullYearTests()
            : base(@"Conformance\15_Native_ECMA_Script_Objects\15.9_Date_Objects\15.9.5_Properties_of_the_Date_Prototype_Object\15.9.5.41_Date.prototype.setUTCFullYear")
        {
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5.41")]
        [TestCase("S15.9.5.41_A1_T1.js", Description = "The Date.prototype property \"setUTCFullYear\" has { DontEnum } attributes")]
        [TestCase("S15.9.5.41_A1_T2.js", Description = "The Date.prototype property \"setUTCFullYear\" has { DontEnum } attributes")]
        [TestCase("S15.9.5.41_A1_T3.js", Description = "The Date.prototype property \"setUTCFullYear\" has { DontEnum } attributes")]
        public void TheDatePrototypePropertySetUTCFullYearHasDontEnumAttributes(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5.41")]
        [TestCase("S15.9.5.41_A2_T1.js", Description = "The \"length\" property of the \"setUTCFullYear\" is 3")]
        public void TheLengthPropertyOfTheSetUTCFullYearIs3(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5.41")]
        [TestCase("S15.9.5.41_A3_T1.js", Description = "The Date.prototype.setUTCFullYear property \"length\" has { ReadOnly, DontDelete, DontEnum } attributes")]
        [TestCase("S15.9.5.41_A3_T2.js", Description = "The Date.prototype.setUTCFullYear property \"length\" has { ReadOnly, DontDelete, DontEnum } attributes")]
        [TestCase("S15.9.5.41_A3_T3.js", Description = "The Date.prototype.setUTCFullYear property \"length\" has { ReadOnly, DontDelete, DontEnum } attributes")]
        public void TheDatePrototypeSetUTCFullYearPropertyLengthHasReadOnlyDontDeleteDontEnumAttributes(string file)
        {
            RunFile(file);
        }
    }
}