// <auto-generated />
namespace IronJS.Tests.UnitTests.Sputnik.Conformance.NativeECMAScriptObjects.DateObjects.PropertiesOfTheDatePrototypeObject
{
    using System;
    using NUnit.Framework;

    [TestFixture]
    public class DatePrototypeSetUTCMinutesTests : SputnikTestFixture
    {
        public DatePrototypeSetUTCMinutesTests()
            : base(@"Conformance\15_Native_ECMA_Script_Objects\15.9_Date_Objects\15.9.5_Properties_of_the_Date_Prototype_Object\15.9.5.33_Date.prototype.setUTCMinutes")
        {
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5.33")]
        [TestCase("S15.9.5.33_A1_T1.js", Description = "The Date.prototype property \"setUTCMinutes\" has { DontEnum } attributes")]
        [TestCase("S15.9.5.33_A1_T2.js", Description = "The Date.prototype property \"setUTCMinutes\" has { DontEnum } attributes")]
        [TestCase("S15.9.5.33_A1_T3.js", Description = "The Date.prototype property \"setUTCMinutes\" has { DontEnum } attributes")]
        public void TheDatePrototypePropertySetUTCMinutesHasDontEnumAttributes(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5.33")]
        [TestCase("S15.9.5.33_A2_T1.js", Description = "The \"length\" property of the \"setUTCMinutes\" is 3")]
        public void TheLengthPropertyOfTheSetUTCMinutesIs3(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5.33")]
        [TestCase("S15.9.5.33_A3_T1.js", Description = "The Date.prototype.setUTCMinutes property \"length\" has { ReadOnly, DontDelete, DontEnum } attributes")]
        [TestCase("S15.9.5.33_A3_T2.js", Description = "The Date.prototype.setUTCMinutes property \"length\" has { ReadOnly, DontDelete, DontEnum } attributes")]
        [TestCase("S15.9.5.33_A3_T3.js", Description = "The Date.prototype.setUTCMinutes property \"length\" has { ReadOnly, DontDelete, DontEnum } attributes")]
        public void TheDatePrototypeSetUTCMinutesPropertyLengthHasReadOnlyDontDeleteDontEnumAttributes(string file)
        {
            RunFile(file);
        }
    }
}