// <auto-generated />
namespace IronJS.Tests.UnitTests.Sputnik.Conformance.NativeECMAScriptObjects.DateObjects.PropertiesOfTheDatePrototypeObject
{
    using System;
    using NUnit.Framework;

    [TestFixture]
    public class DatePrototypeSetFullYearTests : SputnikTestFixture
    {
        public DatePrototypeSetFullYearTests()
            : base(@"Conformance\15_Native_ECMA_Script_Objects\15.9_Date_Objects\15.9.5_Properties_of_the_Date_Prototype_Object\15.9.5.40_Date.prototype.setFullYear")
        {
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5.40")]
        [TestCase("S15.9.5.40_A1_T1.js", Description = "The Date.prototype property \"setFullYear\" has { DontEnum } attributes")]
        [TestCase("S15.9.5.40_A1_T2.js", Description = "The Date.prototype property \"setFullYear\" has { DontEnum } attributes")]
        [TestCase("S15.9.5.40_A1_T3.js", Description = "The Date.prototype property \"setFullYear\" has { DontEnum } attributes")]
        public void TheDatePrototypePropertySetFullYearHasDontEnumAttributes(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5.40")]
        [TestCase("S15.9.5.40_A2_T1.js", Description = "The \"length\" property of the \"setFullYear\" is 3")]
        public void TheLengthPropertyOfTheSetFullYearIs3(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5.40")]
        [TestCase("S15.9.5.40_A3_T1.js", Description = "The Date.prototype.setFullYear property \"length\" has { ReadOnly, DontDelete, DontEnum } attributes")]
        [TestCase("S15.9.5.40_A3_T2.js", Description = "The Date.prototype.setFullYear property \"length\" has { ReadOnly, DontDelete, DontEnum } attributes")]
        [TestCase("S15.9.5.40_A3_T3.js", Description = "The Date.prototype.setFullYear property \"length\" has { ReadOnly, DontDelete, DontEnum } attributes")]
        public void TheDatePrototypeSetFullYearPropertyLengthHasReadOnlyDontDeleteDontEnumAttributes(string file)
        {
            RunFile(file);
        }
    }
}