// <auto-generated />
namespace IronJS.Tests.UnitTests.Sputnik.Conformance.NativeECMAScriptObjects.DateObjects.PropertiesOfTheDatePrototypeObject
{
    using System;
    using NUnit.Framework;

    [TestFixture]
    public class PropertiesOfTheDatePrototypeObjectTests : SputnikTestFixture
    {
        public PropertiesOfTheDatePrototypeObjectTests()
            : base(@"Conformance\15_Native_ECMA_Script_Objects\15.9_Date_Objects\15.9.5_Properties_of_the_Date_Prototype_Object")
        {
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A01_T1.js", Description = "The Date.prototype has the property \"constructor\"")]
        public void TheDatePrototypeHasThePropertyConstructor(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A02_T1.js", Description = "The Date.prototype has the property \"toString\"")]
        public void TheDatePrototypeHasThePropertyToString(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A03_T1.js", Description = "The Date.prototype has the property \"toDateString\"")]
        public void TheDatePrototypeHasThePropertyToDateString(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A04_T1.js", Description = "The Date.prototype has the property \"toTimeString\"")]
        public void TheDatePrototypeHasThePropertyToTimeString(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A05_T1.js", Description = "The Date.prototype has the property \"toLocaleString\"")]
        public void TheDatePrototypeHasThePropertyToLocaleString(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A06_T1.js", Description = "The Date.prototype has the property \"toLocaleDateString\"")]
        public void TheDatePrototypeHasThePropertyToLocaleDateString(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A07_T1.js", Description = "The Date.prototype has the property \"toLocaleTimeString\"")]
        public void TheDatePrototypeHasThePropertyToLocaleTimeString(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A08_T1.js", Description = "The Date.prototype has the property \"valueOf\"")]
        public void TheDatePrototypeHasThePropertyValueOf(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A09_T1.js", Description = "The Date.prototype has the property \"getTime\"")]
        public void TheDatePrototypeHasThePropertyGetTime(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A10_T1.js", Description = "The Date.prototype has the property \"getFullYear\"")]
        public void TheDatePrototypeHasThePropertyGetFullYear(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A11_T1.js", Description = "The Date.prototype has the property \"getUTCFullYear\"")]
        public void TheDatePrototypeHasThePropertyGetUTCFullYear(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A12_T1.js", Description = "The Date.prototype has the property \"getMonth\"")]
        public void TheDatePrototypeHasThePropertyGetMonth(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A13_T1.js", Description = "The Date.prototype has the property \"getUTCMonth\"")]
        public void TheDatePrototypeHasThePropertyGetUTCMonth(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A14_T1.js", Description = "The Date.prototype has the property \"getDate\"")]
        public void TheDatePrototypeHasThePropertyGetDate(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A15_T1.js", Description = "The Date.prototype has the property \"getUTCDate\"")]
        public void TheDatePrototypeHasThePropertyGetUTCDate(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A16_T1.js", Description = "The Date.prototype has the property \"getDay\"")]
        public void TheDatePrototypeHasThePropertyGetDay(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A17_T1.js", Description = "The Date.prototype has the property \"getUTCDay\"")]
        public void TheDatePrototypeHasThePropertyGetUTCDay(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A18_T1.js", Description = "The Date.prototype has the property \"getHours\"")]
        public void TheDatePrototypeHasThePropertyGetHours(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A19_T1.js", Description = "The Date.prototype has the property \"getUTCHours\"")]
        public void TheDatePrototypeHasThePropertyGetUTCHours(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A20_T1.js", Description = "The Date.prototype has the property \"getMinutes\"")]
        public void TheDatePrototypeHasThePropertyGetMinutes(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A21_T1.js", Description = "The Date.prototype has the property \"getUTCMinutes\"")]
        public void TheDatePrototypeHasThePropertyGetUTCMinutes(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A22_T1.js", Description = "The Date.prototype has the property \"getSeconds\"")]
        public void TheDatePrototypeHasThePropertyGetSeconds(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A23_T1.js", Description = "The Date.prototype has the property \"getUTCSeconds\"")]
        public void TheDatePrototypeHasThePropertyGetUTCSeconds(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A24_T1.js", Description = "The Date.prototype has the property \"getMilliseconds\"")]
        public void TheDatePrototypeHasThePropertyGetMilliseconds(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A25_T1.js", Description = "The Date.prototype has the property \"getUTCMilliseconds\"")]
        public void TheDatePrototypeHasThePropertyGetUTCMilliseconds(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A26_T1.js", Description = "The Date.prototype has the property \"getTimezoneOffset\"")]
        public void TheDatePrototypeHasThePropertyGetTimezoneOffset(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A27_T1.js", Description = "The Date.prototype has the property \"setTime\"")]
        public void TheDatePrototypeHasThePropertySetTime(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A28_T1.js", Description = "The Date.prototype has the property \"setMilliseconds\"")]
        public void TheDatePrototypeHasThePropertySetMilliseconds(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A29_T1.js", Description = "The Date.prototype has the property \"setUTCMilliseconds\"")]
        public void TheDatePrototypeHasThePropertySetUTCMilliseconds(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A30_T1.js", Description = "The Date.prototype has the property \"setSeconds\"")]
        public void TheDatePrototypeHasThePropertySetSeconds(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A31_T1.js", Description = "The Date.prototype has the property \"setUTCSeconds\"")]
        public void TheDatePrototypeHasThePropertySetUTCSeconds(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A32_T1.js", Description = "The Date.prototype has the property \"setMinutes\"")]
        public void TheDatePrototypeHasThePropertySetMinutes(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A33_T1.js", Description = "The Date.prototype has the property \"setUTCMinutes\"")]
        public void TheDatePrototypeHasThePropertySetUTCMinutes(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A34_T1.js", Description = "The Date.prototype has the property \"setHours\"")]
        public void TheDatePrototypeHasThePropertySetHours(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A35_T1.js", Description = "The Date.prototype has the property \"setUTCHours\"")]
        public void TheDatePrototypeHasThePropertySetUTCHours(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A36_T1.js", Description = "The Date.prototype has the property \"setDate\"")]
        public void TheDatePrototypeHasThePropertySetDate(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A37_T1.js", Description = "The Date.prototype has the property \"setUTCDate\"")]
        public void TheDatePrototypeHasThePropertySetUTCDate(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A38_T1.js", Description = "The Date.prototype has the property \"setMonth\"")]
        public void TheDatePrototypeHasThePropertySetMonth(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A39_T1.js", Description = "The Date.prototype has the property \"setUTCMonth\"")]
        public void TheDatePrototypeHasThePropertySetUTCMonth(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A40_T1.js", Description = "The Date.prototype has the property \"setFullYear\"")]
        public void TheDatePrototypeHasThePropertySetFullYear(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A41_T1.js", Description = "The Date.prototype has the property \"setUTCFullYear\"")]
        public void TheDatePrototypeHasThePropertySetUTCFullYear(string file)
        {
            RunFile(file);
        }

        [Test]
        [Category("Sputnik Conformance")]
        [Category("ECMA 15.9.5")]
        [TestCase("S15.9.5_A42_T1.js", Description = "The Date.prototype has the property \"toUTCString\"")]
        public void TheDatePrototypeHasThePropertyToUTCString(string file)
        {
            RunFile(file);
        }
    }
}