// <auto-generated />
namespace IronJS.Tests.UnitTests.IE9.chapter11._11_13
{
    using System;
    using NUnit.Framework;

    [TestFixture]
    public class _11_13_1_Tests : IE9TestFixture
    {
        public _11_13_1_Tests() : base(@"chapter11\11.13\11.13.1") { }

        [Test(Description = "simple assignment throws ReferenceError if LeftHandSide is not a reference (number)")] public void _11_13_1__1__1() { RunFile(@"11.13.1-1-1.js"); }
        [Test(Description = "simple assignment throws ReferenceError if LeftHandSide is not a reference (string)")] public void _11_13_1__1__2() { RunFile(@"11.13.1-1-2.js"); }
        [Test(Description = "simple assignment throws ReferenceError if LeftHandSide is not a reference (boolean)")] public void _11_13_1__1__3() { RunFile(@"11.13.1-1-3.js"); }
        [Test(Description = "simple assignment throws ReferenceError if LeftHandSide is not a reference (null)")] public void _11_13_1__1__4() { RunFile(@"11.13.1-1-4.js"); }
        [Test(Description = "simple assignment creates property on the global object if LeftHandSide is an unresolvable reference")] public void _11_13_1__4__1() { RunFile(@"11.13.1-4-1.js"); }
    }
}