// <auto-generated />
namespace IronJS.Tests.UnitTests.Sputnik.Conformance
{
    using System;
    using Microsoft.VisualStudio.TestTools.UnitTesting;

    [TestClass]
    public class ProgramTests : SputnikTestFixture
    {
        public ProgramTests()
            : base(@"Conformance\14_Program")
        {
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 14")]
        [Description("FunctionExpression must be localed in a reacheable fragment of the program")]
        public void S14_A1()
        {
            RunFile(@"S14_A1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 14")]
        [Description("FunctionDeclaration cannot be localed inside an Expression")]
        public void S14_A2()
        {
            RunFile(@"S14_A2.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 14")]
        [Description("Global FunctionDeclaration cannot be defined within the body of another FunctionDeclaration")]
        public void S14_A3()
        {
            RunFile(@"S14_A3.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 14")]
        [Description("The Identifer within a FunctionDeclaration can be written in both letters and unicode")]
        public void S14_A5_T1()
        {
            RunFile(@"S14_A5_T1.js");
        }

        [TestMethod]
        [TestCategory("Sputnik Conformance")]
        [TestCategory("ECMA 14")]
        [Description("The Identifer within a FunctionDeclaration can be written in both letters and unicode")]
        public void S14_A5_T2()
        {
            RunFile(@"S14_A5_T2.js");
        }
    }
}